const wordList= [
  { eng: "provide", kor: "제공하다, 공급하다, 준비하다" },
  { eng: "develop", kor: "개발하다, 발달하다, 발전시키다" },
  { eng: "service", kor: "서비스, 근무, 봉사, 공공 업무" },
  { eng: "inform", kor: "알리다, 통지하다" },
  { eng: "relationship", kor: "관계" },
  { eng: "improve", kor: "향상시키다, 나아지다, 향상하다" },
  { eng: "individual", kor: "개인의, 개인적인개인" },
  { eng: "require", kor: "요구하다, 필요로 하다" },
  { eng: "advise", kor: "충고하다, 조언하다" },
  { eng: "social", kor: "사회의, 사교적인" },
  { eng: "amount", kor: "총액, 총계, 양총계가 ~이 되다" },
  { eng: "behave", kor: "행동하다" },
  { eng: "employ", kor: "고용하다, 쓰다" },
  { eng: "attitude", kor: "태도, 입장" },
  { eng: "research", kor: "연구하다, 조사하다연구, 조사" },
  { eng: "audience", kor: "청중, 관객" },
  { eng: "volunteer", kor: "지원자, 자원봉사, 자원봉사자지원하다, 자원봉사하다" },
  { eng: "influence", kor: "영향, 영향을 미치는 것영향을 미치다" },
  { eng: "terrible", kor: "끔직한, 형편없는, 무서운" },
  { eng: "opportunity", kor: "기회" },
  { eng: "ability", kor: "능력, 재능" },
  { eng: "expense", kor: "비용, 지출" },
  { eng: "local", kor: "지역의, 장소의, 지방의" },
  { eng: "involve", kor: "관련시키다, 포함하다, 관련되다" },
  { eng: "stress", kor: "스트레스, 긴장, 강조강조하다, 압력을 주다" },
  { eng: "therefore", kor: "그러므로, 그 결과" },
  { eng: "positive", kor: "긍정적인, 낙관적인, 확신하는" },
  { eng: "average", kor: "평균의, 보통의평균, 보통 수준평균 ~이다" },
  { eng: "ride", kor: "타다타기, 태우기, 타고가기" },
  { eng: "encourage", kor: "격려하다, 권장하다, 부추기다, 촉구하다" },
  { eng: "determine", kor: "결정하다, 결심하다" },
  { eng: "international", kor: "국제의, 국제적인" },
  { eng: "consume", kor: "소비하다, 먹다" },
  { eng: "impress", kor: "감동시키다, 깊은 인상을 주다" },
  { eng: "object", kor: "물건, 물체, 목표반대하다" },
  { eng: "available", kor: "이용할 수 있는, 쓸모있는, 시간이 있는" },
  { eng: "contain", kor: "들어있다, 포함하다, 함유하다, 억제하다" },
  { eng: "recognize", kor: "인지하다 , 인정하다, 알아보다" },
  { eng: "material", kor: "재료, 소재, 물질물질의" },
  { eng: "comfort", kor: "편안, 평안함, 위안, 위로편안하게 하다, 위로하다" },
  { eng: "emotion", kor: "감정" },
  { eng: "amaze", kor: "놀라게 하다" },
  { eng: "reduce", kor: "줄이다, 낮추다" },
  { eng: "discover", kor: "발견하다, 알아내다" },
  { eng: "decide", kor: "결정하다, 결심하다" },
  { eng: "benefit", kor: "이익, 혜택도움이 되다" },
  { eng: "affect", kor: "영향을 미치다" },
  { eng: "level", kor: "수준, 정도, 수평수평의" },
  { eng: "chemistry", kor: "화학" },
  { eng: "immediate", kor: "즉각적인, 시급한, 직접적인" },
  { eng: "thus", kor: "그러므로, 따라서" },
  { eng: "proper", kor: "적절한, 알맞은" },
  { eng: "performance", kor: "공연, 성과" },
  { eng: "essence", kor: "본질, 정수" },
  { eng: "economic", kor: "경제의, 경제학의" },
  { eng: "cell", kor: "세포" },
  { eng: "focus", kor: "집중하다초점" },
  { eng: "issue", kor: "논란거리, 쟁점, 문제" },
  { eng: "participate", kor: "참여하다, 참가하다(in)" },
  { eng: "demand", kor: "요구, 수요요구하다" },
  { eng: "occur", kor: "발생하다, 일어나다, (생각이) 떠오르다" },
  { eng: "complex", kor: "복잡한복잡체, 복합 건물" },
  { eng: "define", kor: "정의하다, 한계 짓다, 한정하다, 규정하다" },
  { eng: "proud", kor: "자랑스러워하는" },
  { eng: "aware", kor: "인지하는, 인식하고 있는, 알고 있는" },
  { eng: "contact", kor: "연락하다접촉, 연락" },
  { eng: "profession", kor: "직업, 직종, 전문직" },
  { eng: "detail", kor: "세부, 세부사항상술하다" },
  { eng: "approach", kor: "접근하다접근" },
  { eng: "career", kor: "직업, 경력" },
  { eng: "package", kor: "꾸러미, 포장, 포장된 짐포장하다" },
  { eng: "disappear", kor: "사라지다" },
  { eng: "novel", kor: "소설" },
  { eng: "secure", kor: "안전한, 안정된안전하게 하다" },
  { eng: "fashion", kor: "유행, 패션, 방식만들어 내다" },
  { eng: "despite", kor: "~에도 불구하고" },
  { eng: "background", kor: "(그림, 사람, 사건)배경, 배경 지식" },
  { eng: "solution", kor: "해결, 해결책" },
  { eng: "generate", kor: "일으키다, 발생시키다" },
  { eng: "eventually", kor: "결국" },
  { eng: "decrease", kor: "줄다, 줄이다감소" },
  { eng: "recycle", kor: "재활용하다" },
  { eng: "desire", kor: "욕구, 욕망바라다" },
  { eng: "balance", kor: "균형, 은행 잔고균형을 이루다" },
  { eng: "negative", kor: "부정적인" },
  { eng: "follow", kor: "따라가다,  (규칙을) 따르다" },
  { eng: "account", kor: "은행 계좌, 이야기, 설명설명하다" },
  { eng: "publish", kor: "발표하다, 출판하다" },
  { eng: "occasion", kor: "경우, 특별한 일" },
  { eng: "replace", kor: "대체하다" },
  { eng: "constant", kor: "일정한, 불변의(수학에서의) 상수" },
  { eng: "expert", kor: "전문가" },
  { eng: "term", kor: "용어, 기간, 학기" },
  { eng: "relieve", kor: "경감하다, 안도시키다" },
  { eng: "describe", kor: "묘사하다, 표현하다" },
  { eng: "biology", kor: "생물학" },
  { eng: "due", kor: "만기의, ~하기로 되어 있는" },
  { eng: "equipment", kor: "장치, 장비" },
  { eng: "congratulate", kor: "축하하다" },
  { eng: "birth", kor: "탄생" },
  { eng: "compose", kor: "구성하다, 작곡하다, 작문하다" },
  { eng: "genius", kor: "천재, 천재성" },
  { eng: "reflect", kor: "반영하다, 반사하다, 숙고하다" },
  { eng: "cause", kor: "~의 원인이 되다, 야기하다원인" },
  { eng: "frequent", kor: "빈번한(장소,모임에) 자주 가다" },
  { eng: "factor", kor: "요인, 요소" },
  { eng: "extreme", kor: "극단의극단" },
  { eng: "tend", kor: "~하는 경향이 있다, 돌보다" },
  { eng: "politics", kor: "정치, 정치학" },
  { eng: "insist", kor: "주장하다" },
  { eng: "extend", kor: "연장하다, 넓히다" },
  { eng: "lonely", kor: "외로운" },
  { eng: "habitat", kor: "서식지, 주거지" },
  { eng: "mental", kor: "정신의" },
  { eng: "steady", kor: "안정된, 한결같은, 꾸준한" },
  { eng: "exchange", kor: "교환하다" },
  { eng: "active", kor: "활동적인, 적극적인" },
  { eng: "species", kor: "(생물분류상의) 종" },
  { eng: "athletic", kor: "운동의, 운동경기의" },
  { eng: "dental", kor: "치아의" },
  { eng: "delight", kor: "기쁨기쁘게 하다" },
  { eng: "confident", kor: "자신 있는" },
  { eng: "gradually", kor: "점차, 서서히" },
  { eng: "shadow", kor: "그림자그늘지게 하다" },
  { eng: "access", kor: "접근, 이용접근하다" },
  { eng: "announce", kor: "발표하다, 알리다" },
  { eng: "allow", kor: "허락하다, 인정하다" },
  { eng: "firm", kor: "확고한, 단단한회사" },
  { eng: "vary", kor: "바꾸다, 변하다, 다르다" },
  { eng: "injure", kor: "상처를 입히다, 손상시키다" },
  { eng: "permit", kor: "허용하다" },
  { eng: "response", kor: "응답, 반응" },
  { eng: "threat", kor: "위협, 협박" },
  { eng: "electricity", kor: "전기" },
  { eng: "disabled", kor: "장애를 가진, 무능력하게 된" },
  { eng: "lack", kor: "부족~이 부족하다" },
  { eng: "signify", kor: "의미하다, 중요하다" },
  { eng: "concentrate", kor: "집중하다" },
  { eng: "emphasize", kor: "강조하다" },
  { eng: "astronomy", kor: "천문학" },
  { eng: "flood", kor: "홍수범람시키다" },
  { eng: "fuel", kor: "연료연료를 가하다" },
  { eng: "manufacture", kor: "제조하다제조(업), 제품" },
  { eng: "movement", kor: "움직임, 운동" },
  { eng: "capable", kor: "~을 할 수 있는, 유능한" },
  { eng: "combine", kor: "결합하다, 겸비하다" },
  { eng: "gene", kor: "유전자" },
  { eng: "increase", kor: "(수량이) 증가하다증가, 이자" },
  { eng: "victim", kor: "희생, 피해자" },
  { eng: "pressure", kor: "압력, 압박압력을 가하다" },
  { eng: "accompany", kor: "동반하다, 수반하다" },
  { eng: "frustrate", kor: "좌절시키다" },
  { eng: "construct", kor: "건설하다" },
  { eng: "dwindle", kor: "점점 줄어들다, 저하되다" },
  { eng: "commerce", kor: "상업, 교역" },
  { eng: "entertain", kor: "즐겁게 하다" },
  { eng: "predict", kor: "예언하다, 예측하다" },
  { eng: "apologize", kor: "사과하다" },
  { eng: "sight", kor: "시야, 광경, 시력" },
  { eng: "quantity", kor: "양" },
  { eng: "conclude", kor: "결론짓다, 끝내다" },
  { eng: "donate", kor: "기부하다" },
  { eng: "personality", kor: "개성, 성격, 특색" },
  { eng: "struggle", kor: "싸우다, 노력하다투쟁, 노력" },
  { eng: "advantage", kor: "유리한 점, 이점" },
  { eng: "variety", kor: "다양, 다양성" },
  { eng: "enable", kor: "가능하게 하다" },
  { eng: "instruction", kor: "지시, 제품 사용 설명서, 가르침" },
  { eng: "assume", kor: "추정하다, (태도 등을) 취하다" },
  { eng: "attempt", kor: "시도하다시도" },
  { eng: "incredible", kor: "믿을 수 없는, (믿기 어려울 만큼) 굉장한" },
  { eng: "feature", kor: "특징, 특집 기사, 얼굴 생김새~을 특징으로 하다, 주연하다" },
  { eng: "confuse", kor: "혼동하다, 혼란시키다" },
  { eng: "electronic", kor: "전자의" },
  { eng: "absorb", kor: "흡수하다, (사람, 마음을) 열중시키다" },
  { eng: "indicate", kor: "가리키다, 나타내다" },
  { eng: "analyze", kor: "분석하다" },
  { eng: "stock", kor: "재고품, 저장, 가축저장하다, (물품을) 들여놓다" },
  { eng: "resident", kor: "거주자" },
  { eng: "labor", kor: "노동, 산고노동하다" },
  { eng: "remark", kor: "의견, 주목의견을 말하다, ~에 주목하다" },
  { eng: "moral", kor: "도덕적인" },
  { eng: "embarrassed", kor: "당황한" },
  { eng: "claim", kor: "주장하다요구, 주장" },
  { eng: "reasonable", kor: "논리적인, 분별력 있는" },
  { eng: "interrupt", kor: "방해하다, 중단하다" },
  { eng: "discount", kor: "할인할인하다" },
  { eng: "creature", kor: "생물, 피조물" },
  { eng: "heal", kor: "치료하다, 낫게 하다" },
  { eng: "establish", kor: "설립하다, 확립하다, 제정하다" },
  { eng: "revolution", kor: "혁명, 갑작스러운 변화, 회전" },
  { eng: "criticize", kor: "비난하다" },
  { eng: "convince", kor: "확신시키다, 납득시키다" },
  { eng: "efficient", kor: "효율적인, 유능한" },
  { eng: "stranger", kor: "낯선 사람, 문외한" },
  { eng: "tide", kor: "조수, 흐름" },
  { eng: "obtain", kor: "획득하다, 통용되다, 행해지다" },
  { eng: "assist", kor: "도움을 주다" },
  { eng: "disaster", kor: "재앙, 재난, 재해" },
  { eng: "terrific", kor: "굉장한, 훌륭한" },
  { eng: "specific", kor: "구체적인, 특정한" },
  { eng: "react", kor: "반응하다, 반작용하다" },
  { eng: "independent", kor: "독립적인" },
  { eng: "theory", kor: "이론" },
  { eng: "qualify", kor: "자격을 얻다" },
  { eng: "consider", kor: "숙고하다, 고려하다" },
  { eng: "recall", kor: "상기하다, 철회하다, 회수하다; 상기, 철회" },
  { eng: "risk", kor: "위험; 위험을 감수하다" },
  { eng: "treatment", kor: "취급, 대우, 치료(법)" },
  { eng: "engage", kor: "관여하다, 약속하다, 약혼하다" },
  { eng: "motivate", kor: "동기를 부여하다" },
  { eng: "clue", kor: "실마리, 단서" },
  { eng: "cancer", kor: "암, 악성 종양" },
  { eng: "elder", kor: "나이가 위인; 연장자" },
  { eng: "depress", kor: "우울하게 하다, 의기소침(낙담)하게 하다" },
  { eng: "fascinate", kor: "매료시키다, 마음을 빼앗다" },
  { eng: "violent", kor: "난폭한, 폭력적인" },
  { eng: "alarm", kor: "놀람, 경보" },
  { eng: "edge", kor: "가장자리, 날카로움, 우위" },
  { eng: "deserve", kor: "~을 받을 만하다(가치가 있다)" },
  { eng: "route", kor: "길, 통로, 항로" },
  { eng: "psychology", kor: "심리, 심리학" },
  { eng: "passion", kor: "열정" },
  { eng: "import", kor: "수입하다, 의미하다; 수입" },
  { eng: "purchase", kor: "구매하다; 구매" },
  { eng: "conscience", kor: "양심" },
  { eng: "pose", kor: "자세를 취하다, (문제를) 제기하다; 자세" },
  { eng: "length", kor: "길이" },
  { eng: "severe", kor: "심한, 엄격한" },
  { eng: "decade", kor: "10년, 10년간" },
  { eng: "occupy", kor: "(시간, 장소를) 차지하다, 전념하다" },
  { eng: "acquire", kor: "습득하다" },
  { eng: "interact", kor: "상호 작용하다" },
  { eng: "brief", kor: "간단한; 간단한 보고; 간단히 알리다" },
  { eng: "observe", kor: "관찰하다, ~을 보다, 준수하다" },
  { eng: "poetry", kor: "시, 운문" },
  { eng: "salary", kor: "급료, 봉급" },
  { eng: "grain", kor: "곡물, 낟알" },
  { eng: "meaningful", kor: "의미 있는, 의미심장한" },
  { eng: "weed", kor: "잡초; 잡초를 제거하다" },
  { eng: "survival", kor: "생존" },
  { eng: "comment", kor: "논평, 주석 논평하다" },
  { eng: "leap", kor: "뛰다, 도약하다 도약" },
  { eng: "survey", kor: "둘러보다, 조사하다 설문 조사" },
  { eng: "typical", kor: "전형적인, 대표적인" },
  { eng: "mere", kor: "단지 ~에 불과한" },
  { eng: "mechanic", kor: "기계공" },
  { eng: "mood", kor: "분위기, 기분" },
  { eng: "approve", kor: "승인하다, 찬성하다" },
  { eng: "rural", kor: "시골의" },
  { eng: "finance", kor: "재정, 자금 자금을 조달하다" },
  { eng: "seek", kor: "찾다, 추구하다" },
  { eng: "operation", kor: "작업, 운영, 수술" },
  { eng: "crime", kor: "범죄" },
  { eng: "awful", kor: "끔찍한, 지독한" },
  { eng: "series", kor: "연속, 시리즈물" },
  { eng: "exhausted", kor: "고갈된, 기진맥진한" },
  { eng: "absolute", kor: "완전한, 절대적인" },
  { eng: "surround", kor: "둘러싸다" },
  { eng: "display", kor: "전시하다, 나타내다 전시" },
  { eng: "policy", kor: "정책, 수단" },
  { eng: "mass", kor: "덩어리, 집단" },
  { eng: "committee", kor: "위원회" },
  { eng: "accurate", kor: "정확한" },
  { eng: "arrange", kor: "정리하다, 준비하다" },
  { eng: "facility", kor: "시설, 편의" },
  { eng: "consult", kor: "상담하다, 참고하다" },
  { eng: "refer", kor: "언급하다, 위탁하다" },
  { eng: "attach", kor: "붙이다, 첨부하다" },
  { eng: "recover", kor: "회복하다, 되찾다" },
  { eng: "reward", kor: "보상 보답하다" },
  { eng: "enormous", kor: "엄청난, 거대한" },
  { eng: "domestic", kor: "국내의, 가정의" },
  { eng: "wealth", kor: "부, 재산" },
  { eng: "elementary", kor: "초보의, 기초적인" },
  { eng: "gap", kor: "격차, 틈" },
  { eng: "except", kor: "~을 제외하고 제외하다" },
  { eng: "journey", kor: "여행" },
  { eng: "plain", kor: "평범한, 명백한" },
  { eng: "downtown", kor: "도심 도심의 도심지에서" },
  { eng: "previous", kor: "이전의, 앞의" },
  { eng: "produce", kor: "생산하다, 제조하다" },
  { eng: "remain", kor: "여전히 ~이다, 남다" },
  { eng: "break", kor: "깨다, 고장내다" },
  { eng: "slight", kor: "약간의, 경미한" },
  { eng: "include", kor: "포함하다" },
  { eng: "delay", kor: "연기하다, 미루다지연" },
  { eng: "file", kor: "서류철파일에 철하다, 제기하다" },
  { eng: "ethic", kor: "윤리" },
  { eng: "instant", kor: "즉각의, 즉석의순간" },
  { eng: "reveal", kor: "폭로하다, 드러내다" },
  { eng: "breed", kor: "낳다, 양육하다" },
  { eng: "leisure", kor: "여가한가한" },
  { eng: "urban", kor: "도시의" },
  { eng: "witness", kor: "목격자목격하다" },
  { eng: "admit", kor: "인정하다, 입학을 허가하다" },
  { eng: "muscle", kor: "근육, 힘" },
  { eng: "device", kor: "장치, 고안, 방책" },
  { eng: "suppose", kor: "추측하다, 가정하다" },
  { eng: "owe", kor: "빚지고 있다" },
  { eng: "intend", kor: "~할 작정이다, 의도하다" },
  { eng: "aspect", kor: "면, 관점" },
  { eng: "potential", kor: "잠재적인잠재력" },
  { eng: "award", kor: "상(상 등을) 수여하다" },
  { eng: "preserve", kor: "보존하다, 보호하다" },
  { eng: "spot", kor: "장소, 점발견하다" },
  { eng: "underground", kor: "지하의, 비밀의지하" },
  { eng: "consequence", kor: "결과, 중요성" },
  { eng: "target", kor: "목표목표로 삼다" },
  { eng: "unless", kor: "만약 ~이 아니면" },
  { eng: "accomplish", kor: "이루다, 성취하다" },
  { eng: "adopt", kor: "입양하다, 채택하다" },
  { eng: "unique", kor: "독특한, 유일한" },
  { eng: "slip", kor: "미끄러지다, 실수하다종이 조각" },
  { eng: "civilization", kor: "문명" },
  { eng: "row", kor: "열, 줄배를 젓다" },
  { eng: "horizon", kor: "지평선" },
  { eng: "atmosphere", kor: "대기, 분위기" },
  { eng: "label", kor: "꼬리표, 상표라벨을 붙이다" },
  { eng: "decorate", kor: "장식하다, ~에게 훈장을 주다" },
  { eng: "identify", kor: "~임을 확인하다, 식별하다, 동일시하다" },
  { eng: "standard", kor: "표준, 기준 기준의, 표준의" },
  { eng: "scale", kor: "규모, 저울, 비늘" },
  { eng: "evident", kor: "명백한" },
  { eng: "seldom", kor: "거의 ~않는" },
  { eng: "secretary", kor: "비서, 장관" },
  { eng: "basis", kor: "원리, 기초" },
  { eng: "automatic", kor: "자동적인, 기계적인" },
  { eng: "region", kor: "지역" },
  { eng: "rise", kor: "일어나다, 오르다 상승" },
  { eng: "addict", kor: "중독시키다 중독자" },
  { eng: "disappoint", kor: "실망시키다" },
  { eng: "artificial", kor: "인공적인, 인조의" },
  { eng: "possess", kor: "소유하다, ~의 마음을 사로잡다" },
  { eng: "substance", kor: "물질, 본질, 실체" },
  { eng: "realistic", kor: "현실적인, 현실주의의" },
  { eng: "encounter", kor: "(우연히) 만나다 마주침" },
  { eng: "differ", kor: "다르다, 의견을 달리하다" },
  { eng: "principle", kor: "원칙, 원리" },
  { eng: "memorize", kor: "기억하다" },
  { eng: "physics", kor: "물리학" },
  { eng: "evaluate", kor: "평가하다" },
  { eng: "tremendous", kor: "굉장한, 무시무시한" },
  { eng: "application", kor: "적용, 신청" },
  { eng: "vote", kor: "투표 투표하다" },
  { eng: "spread", kor: "퍼짐, 확산 펼치다, 퍼지다" },
  { eng: "impact", kor: "충격, 영향 충격을 주다" },
  { eng: "cooperate", kor: "협력하다" },
  { eng: "emit", kor: "(빛, 열, 소리 등을)방출하다" },
  { eng: "request", kor: "요청 요청하다" },
  { eng: "guarantee", kor: "보장하다 보증" },
  { eng: "resist", kor: "저항하다" },
  { eng: "fulfill", kor: "달성하다, 이행하다" },
  { eng: "stink", kor: "역겹다, 악취를 풍기다" },
  { eng: "grant", kor: "수여하다, 승인하다" },
  { eng: "rely", kor: "의지하다, 믿다" },
  { eng: "permanent", kor: "영원한, 영구적인" },
  { eng: "emergency", kor: "비상 사태" },
  { eng: "rid", kor: "제거하다" },
  { eng: "theme", kor: "주제, 화제" },
  { eng: "hesitate", kor: "주저하다, 망설이다" },
  { eng: "location", kor: "위치, 장소" },
  { eng: "restrict", kor: "제한하다, 한정하다" },
  { eng: "organism", kor: "유기체, 생물" },
  { eng: "resolve", kor: "해결하다, 결심하다" },
  { eng: "offer", kor: "제공하다, 제안하다" },
  { eng: "distribute", kor: "분배하다, 분포시키다" },
  { eng: "rainforest", kor: "열대우림" },
  { eng: "circumstance", kor: "상황, 환경" },
  { eng: "interpret", kor: "해석하다, 통역하다" },
  { eng: "suitable", kor: "적절한, 적합한" },
  { eng: "curve", kor: "곡선, 속임수" },
  { eng: "annoy", kor: "괴롭히다, 귀찮게 하다" },
  { eng: "frighten", kor: "겁먹게 하다" },
  { eng: "estimate", kor: "평가하다견적, 평가" },
  { eng: "refuse", kor: "거절하다" },
  { eng: "adventure", kor: "모험위험에 빠뜨리다" },
  { eng: "entrance", kor: "입구, 입장" },
  { eng: "persuade", kor: "설득하다" },
  { eng: "perceive", kor: "인지하다, 인식하다" },
  { eng: "recite", kor: "암송하다" },
  { eng: "gather", kor: "모으다" },
  { eng: "cabin", kor: "객실, 선실, 오두막집" },
  { eng: "gear", kor: "장비,  기어맞게 조정하다" },
  { eng: "ray", kor: "광선" },
  { eng: "release", kor: "놓아주다, 방출하다석방, 발표" },
  { eng: "rank", kor: "지위, 계급매기다, (등급을)차지하다" },
  { eng: "symphony", kor: "교향곡" },
  { eng: "envy", kor: "부러워하다부러움" },
  { eng: "corporate", kor: "회사의, 법인의" },
  { eng: "alternative", kor: "대안대안의" },
  { eng: "retire", kor: "은퇴하다" },
  { eng: "appeal", kor: "호소하다, 관심을 끌다호소, 항의" },
  { eng: "identical", kor: "동일한, 일란성의" },
  { eng: "investment", kor: "투자" },
  { eng: "autograph", kor: "서명서명하다" },
  { eng: "slave", kor: "노예" },
  { eng: "harm", kor: "손해, 손상해치다" },
  { eng: "authority", kor: "권위, 당국" },
  { eng: "innocence", kor: "결백, 무죄, 순진" },
  { eng: "infant", kor: "유아, 유치원생" },
  { eng: "calculate", kor: "계산하다" },
  { eng: "charity", kor: "자선 단체" },
  { eng: "receive", kor: "받다" },
  { eng: "whereas", kor: "그런데, ~에 반해서" },
  { eng: "board", kor: "판자, 게시판타다" },
  { eng: "ignorant", kor: "무지한, 무식한" },
  { eng: "depend", kor: "의존하다, ~에 달려 있다" },
  { eng: "pure", kor: "순수한, 깨끗한" },
  { eng: "extinct", kor: "멸종된, 사라진" },
  { eng: "household", kor: "가정가정의" },
  { eng: "chapter", kor: "(책의) 장, 시기, 사제단" },
  { eng: "refund", kor: "환불하다환불금" },
  { eng: "institute", kor: "기관, 협회" },
  { eng: "lately", kor: "최근에" },
  { eng: "accept", kor: "받아들이다" },
  { eng: "ashamed", kor: "부끄러워하는" },
  { eng: "dense", kor: "밀집한, (앞이 안 보이게) 짙은" },
  { eng: "rescue", kor: "구출하다구출" },
  { eng: "continue", kor: "계속하다" },
  { eng: "destination", kor: "목적지" },
  { eng: "expand", kor: "확장되다, 확장시키다" },
  { eng: "evolution", kor: "진화, 발전" },
  { eng: "hire", kor: "고용하다" },
  { eng: "isolate", kor: "고립시키다, 격리시키다" },
  { eng: "gravity", kor: "중력" },
  { eng: "genuine", kor: "진짜의, 진실된" },
  { eng: "statue", kor: "조각상" },
  { eng: "compete", kor: "경쟁하다" },
  { eng: "military", kor: "군의, 군사의군, 군대" },
  { eng: "logic", kor: "논리, 논리학" },
  { eng: "commit", kor: "(죄 등을) 저지르다, 약속하다, 헌신하다" },
  { eng: "sensible", kor: "합리적인, 현명한" },
  { eng: "sum", kor: "금액, 합계" },
  { eng: "conserve", kor: "보존하다, 보호하다" },
  { eng: "swing", kor: "흔들다, 휘두르다" },
  { eng: "marriage", kor: "결혼, 결혼 생활" },
  { eng: "reproduce", kor: "번식하다, 재생하다, 복제하다" },
  { eng: "tone", kor: "음조, 어조, 억양 조화하다, 탄력있게 만들다" },
  { eng: "concept", kor: "개념" },
  { eng: "invitation", kor: "초대" },
  { eng: "precise", kor: "정확한, 정밀한" },
  { eng: "formal", kor: "공식적인, 격식을 차린" },
  { eng: "particle", kor: "작은 조각, 입자" },
  { eng: "cancel", kor: "취소하다" },
  { eng: "return", kor: "돌아가다, 돌려주다돌아감, 귀향" },
  { eng: "departure", kor: "출발, 떠남, 일탈" },
  { eng: "apparent", kor: "명백한" },
  { eng: "visual", kor: "눈에 보이는, 시각의" },
  { eng: "agriculture", kor: "농업" },
  { eng: "rite", kor: "의식, 의례" },
  { eng: "poverty", kor: "가난" },
  { eng: "sculpture", kor: "조각상" },
  { eng: "descend", kor: "내려가다, 내려오다" },
  { eng: "leak", kor: "새다새는 구멍" },
  { eng: "portion", kor: "부분, 1인분" },
  { eng: "companion", kor: "친구, 동료" },
  { eng: "diligent", kor: "근면한" },
  { eng: "distinct", kor: "뚜렷한, 다른" },
  { eng: "component", kor: "구성 요소구성하는" },
  { eng: "current", kor: "현재의, 지금의" },
  { eng: "universal", kor: "보편적인, 전 세계의" },
  { eng: "trap", kor: "덫가두다" },
  { eng: "eager", kor: "갈망하는" },
  { eng: "legal", kor: "법률의, 합법적인" },
  { eng: "demonstrate", kor: "입증하다, 시위하다, 설명하다" },
  { eng: "democracy", kor: "민주주의" },
  { eng: "mature", kor: "성숙한성숙하다" },
  { eng: "brilliant", kor: "빛나는, 훌륭한" },
  { eng: "annual", kor: "연간의, 해마다의" },
  { eng: "faith", kor: "믿음, 신념" },
  { eng: "spare", kor: "(시간, 돈을) 할애하다, (고생을) 면하게 하다여분의" },
  { eng: "transfer", kor: "이동하다, 옮기다, 환승하다이환승" },
  { eng: "refrigerator", kor: "냉장고" },
  { eng: "oppose", kor: "반대하다" },
  { eng: "desperate", kor: "절망적인, 필사적인" },
  { eng: "remote", kor: "멀리 떨어진, 원격 조정의" },
  { eng: "offend", kor: "불쾌하게 하다" },
  { eng: "awake", kor: "깨어있는" },
  { eng: "aim", kor: "목표로 하다, 겨누다목표" },
  { eng: "option", kor: "선택, 선택권" },
  { eng: "insight", kor: "통찰력" },
  { eng: "achieve", kor: "이루다, 성취하다" },
  { eng: "civil", kor: "시민의, 민간의" },
  { eng: "pause", kor: "잠시 멈추다중단" },
  { eng: "prove", kor: "입증하다" },
  { eng: "lecture", kor: "강의강의를 하다" },
  { eng: "minor", kor: "사소한, 미성년자부전공하다" },
  { eng: "duty", kor: "의무, 관세" },
  { eng: "vigor", kor: "활력" },
  { eng: "organize", kor: "조직하다, 구성하다" },
  { eng: "chief", kor: "우두머리우두머리의, 주요한" },
  { eng: "complicated", kor: "복잡한" },
  { eng: "digest", kor: "소화하다요약" },
  { eng: "shortage", kor: "부족, 결함" },
  { eng: "laboratory", kor: "실험실실험의" },
  { eng: "arrive", kor: "도착하다" },
  { eng: "generous", kor: "관대한, 넉넉한" },
  { eng: "laundry", kor: "세탁물" },
  { eng: "transform", kor: "변형시키다, 변환하다" },
  { eng: "discipline", kor: "규율, 훈련훈육하다, 징계하다" },
  { eng: "forbid", kor: "금지하다" },
  { eng: "ultimate", kor: "궁극적인, 최후의" },
  { eng: "thrive", kor: "번영하다, 발전하다" },
  { eng: "conversation", kor: "대화, 회담" },
  { eng: "bet", kor: "돈을 걸다, 내기를 하다내기" },
  { eng: "royal", kor: "왕족의, 왕의" },
  { eng: "ruin", kor: "망치다, 파멸시키다파멸, 파산" },
  { eng: "worship", kor: "숭배하다, 예배하다숭배, 예배" },
  { eng: "evil", kor: "사악한악" },
  { eng: "scarce", kor: "부족한, 드문" },
  { eng: "afterward", kor: "나중에, 그 후에" },
  { eng: "client", kor: "고객, 의뢰인" },
  { eng: "insure", kor: "보험을 계약하다, 안전하게 하다" },
  { eng: "fancy", kor: "공상화려한공상하다" },
  { eng: "surgery", kor: "외과 수술" },
  { eng: "assign", kor: "할당하다, 지정하다" },
  { eng: "regulate", kor: "규제하다, 조절하다" },
  { eng: "shelf", kor: "선반" },
  { eng: "utility", kor: "공익사업, 유용성" },
  { eng: "necessity", kor: "필요, 필수, 필수품" },
  { eng: "yield", kor: "생산하다, 굴복하다, 양도하다수확(물)" },
  { eng: "decline", kor: "감소, 쇠퇴감소하다, 쇠퇴하다, 거절하다" },
  { eng: "coincidence", kor: "우연의 일치, 동시에 일어난 사건" },
  { eng: "aside", kor: "한쪽으로, 제쳐 두고" },
  { eng: "contemporary", kor: "현대의, 동시대의" },
  { eng: "bless", kor: "축복하다, 감사하다" },
  { eng: "explain", kor: "설명하다" },
  { eng: "prior", kor: "이전의, 우선하는" },
  { eng: "tolerate", kor: "참다, 용인하다" },
  { eng: "measure", kor: "측정하다측정, 수단" },
  { eng: "abstract", kor: "추상적인추상, 개요" },
  { eng: "cottage", kor: "오두막집" },
  { eng: "correct", kor: "올바른, 정확한바로잡다, 정정하다" },
  { eng: "confirm", kor: "확인하다, 입증하다, (결심을) 굳게 하다" },
  { eng: "imitate", kor: "모방하다" },
  { eng: "prey", kor: "먹이, 희생자" },
  { eng: "defeat", kor: "패배시키다패배" },
  { eng: "illustrate", kor: "설명하다, (분명히) 보여주다, 삽화를 넣다" },
  { eng: "fuse", kor: "퓨즈, 도화선융합하다" },
  { eng: "pupil", kor: "학생, 눈동자" },
  { eng: "intellect", kor: "지성" },
  { eng: "spice", kor: "향신료, 양념" },
  { eng: "tempt", kor: "유혹하다 (관심을) 끌다" },
  { eng: "inspire", kor: "영감을 주다, 고무시키다, 격려하다" },
  { eng: "dine", kor: "식사하다, 만찬을 대접하다" },
  { eng: "literally", kor: "문자 그대로" },
  { eng: "appropriate", kor: "적절한" },
  { eng: "resort", kor: "휴양지, 의지의지하다, 자주 가다" },
  { eng: "grab", kor: "움켜쥐다움켜쥠" },
  { eng: "propose", kor: "제안하다, 청혼하다" },
  { eng: "wreck", kor: "난파선, 사고난파시키다" },
  { eng: "document", kor: "문서, 서류기록하다" },
  { eng: "suspect", kor: "의심하다용의자" },
  { eng: "alien", kor: "외국의, 이질적인외국인, 외계인" },
  { eng: "prohibit", kor: "금지하다" },
  { eng: "install", kor: "설치하다" },
  { eng: "triumph", kor: "승리승리하다" },
  { eng: "scholarship", kor: "장학금, 학문" },
  { eng: "execute", kor: "실행하다, 처형하다" },
  { eng: "ensure", kor: "반드시 ~하게 하다, 보장하다, 확실하게 하다" },
  { eng: "receipt", kor: "영수증" },
  { eng: "defect", kor: "결점, 결함(국가•당 등을) 버리다" },
  { eng: "trait", kor: "특징, 특성" },
  { eng: "modest", kor: "겸손한, 미천한, 알맞은" },
  { eng: "virtual", kor: "실제의, 가상의, 사실상의" },
  { eng: "compare", kor: "비교하다, 비유하다" },
  { eng: "address", kor: "주소, 연설, 인사말연설하다, 접근하다" },
  { eng: "inner", kor: "안쪽의, 내적인, 내부의" },
  { eng: "contrary", kor: "반대의, 불리한정반대, 반대의 것" },
  { eng: "split", kor: "나뉘다, 분열되다, 찢다, 쪼개다틈, 분열" },
  { eng: "supervise", kor: "감독하다, 관리하다, 통제하다" },
  { eng: "inhabit", kor: "~에 살다, 거주하다" },
  { eng: "appear", kor: "나타나다, ~인 것 같다" },
  { eng: "commute", kor: "통근하다통근(거리)" },
  { eng: "earthquake", kor: "지진, (사회•정치적) 대변동" },
  { eng: "enroll", kor: "등록하다, 입학하다" },
  { eng: "debate", kor: "논쟁하다, 토론하다논쟁, 토론" },
  { eng: "abandon", kor: "버리다, 포기하다" },
  { eng: "conquer", kor: "정복하다, 이기다, 극복하다" },
  { eng: "nevertheless", kor: "그럼에도 불구하고" },
  { eng: "seal", kor: "봉인하다봉인, 도장, 바다표범" },
  { eng: "greed", kor: "탐욕, 식탐" },
  { eng: "contract", kor: "계약, 계약서계약하다, 수축하다" },
  { eng: "nutrition", kor: "영양" },
  { eng: "retail", kor: "소매소매하다소매로" },
  { eng: "prejudice", kor: "편견, 선입관편견을 갖게 하다" },
  { eng: "register", kor: "등록하다, 기재하다등록부" },
  { eng: "agency", kor: "기관, 대행사, 대리점" },
  { eng: "nurture", kor: "양육하다, 양성하다, 교육하다교육, 양육" },
  { eng: "priest", kor: "성직자" },
  { eng: "elegant", kor: "우아한, 고상한" },
  { eng: "impose", kor: "부과하다, 강요하다" },
  { eng: "arise", kor: "발생하다, 일어나다, 생겨나다" },
  { eng: "modify", kor: "수정하다, 변형하다" },
  { eng: "masterpiece", kor: "대표작, 대작, 명작" },
  { eng: "harsh", kor: "가혹한, 거친" },
  { eng: "drought", kor: "가뭄" },
  { eng: "criteria", kor: "기준, 표준 (criterion의 복수형)" },
  { eng: "extraordinary", kor: "비범한, 기이한, 놀라운" },
  { eng: "dim", kor: "희미한, 어둑한 어둑하게 하다" },
  { eng: "general", kor: "일반적인, 전반적인 장군" },
  { eng: "scream", kor: "비명을 지르다 비명" },
  { eng: "spill", kor: "흘리다, 쏟다" },
  { eng: "glare", kor: "노려보다, 반짝 반짝 빛나다 노려봄, 눈부신 빛" },
  { eng: "swallow", kor: "삼킴, 제비 삼키다" },
  { eng: "usual", kor: "늘 하는, 흔히 있는" },
  { eng: "routine", kor: "틀에 박힌 일 일상적인, 지루한" },
  { eng: "eliminate", kor: "제거하다, 삭제하다" },
  { eng: "deny", kor: "부인하다, 거절하다" },
  { eng: "sensitive", kor: "민감한, 예민한" },
  { eng: "tragic", kor: "비극적인" },
  { eng: "deprive", kor: "빼앗다, 강탈하다" },
  { eng: "conscious", kor: "의식하는, 의식이 있는" },
  { eng: "interfere", kor: "간섭하다" },
  { eng: "temporary", kor: "임시의" },
  { eng: "council", kor: "의회" },
  { eng: "adolescent", kor: "청소년 청소년의" },
  { eng: "arctic", kor: "북극의" },
  { eng: "capture", kor: "붇잡다, 점유하다" },
  { eng: "dilute", kor: "묽은 묽게 하다, 약화시키다" },
  { eng: "associate", kor: "연상하다, 어울리다 동료" },
  { eng: "figure", kor: "숫자, 인물 이해하다, 계산하다" },
  { eng: "warehouse", kor: "창고" },
  { eng: "crew", kor: "승무원, (특별한 기술의)팀 승무원으로 일하다" },
  { eng: "barrier", kor: "장벽, 장애물" },
  { eng: "pedestrian", kor: "보행자 보행자의" },
  { eng: "glance", kor: "흘꿋 보다 흘끗 봄" },
  { eng: "errand", kor: "심부름" },
  { eng: "irritate", kor: "짜증나게 하다, 자극하다" },
  { eng: "welfare", kor: "복지, 행복" },
  { eng: "cruel", kor: "잔인한, 비참한" },
  { eng: "fold", kor: "주름 접다" },
  { eng: "trial", kor: "재판, 시험" },
  { eng: "tribe", kor: "부족" },
  { eng: "profound", kor: "깊은, 심오한" },
  { eng: "tradition", kor: "전통" },
  { eng: "distinguish", kor: "구별하다" },
  { eng: "statement", kor: "진술, 성명, 진술서" },
  { eng: "prevail", kor: "만연하다, 우세하다" },
  { eng: "widespread", kor: "널리 퍼진" },
  { eng: "result", kor: "결과" },
  { eng: "fade", kor: "사라지다, (색깔이) 바래다" },
  { eng: "progress", kor: "진전, 진보진보하다" },
  { eng: "weapon", kor: "무기" },
  { eng: "drastic", kor: "과감한, 격렬한" },
  { eng: "reinforcement", kor: "병력 증강, 강화" },
  { eng: "wonder", kor: "궁금해하다, 놀라다놀라움" },
  { eng: "pile", kor: "더미쌓다" },
  { eng: "protect", kor: "보호하다" },
  { eng: "infection", kor: "감염" },
  { eng: "stiffen", kor: "굳어지다" },
  { eng: "endanger", kor: "위험에 빠뜨리다" },
  { eng: "adjust", kor: "조절하다, 적응하다" },
  { eng: "peer", kor: "동료, 또래자세히 들여다보다" },
  { eng: "renew", kor: "새롭게 하다, 연장하다" },
  { eng: "germ", kor: "세균, 싹, 근원" },
  { eng: "atom", kor: "원자" },
  { eng: "realize", kor: "깨닫다, 실현하다" },
  { eng: "enrich", kor: "부유하게 하다" },
  { eng: "noble", kor: "고결한, 귀족의" },
  { eng: "repair", kor: "수리하다수리" },
  { eng: "candidate", kor: "후보자" },
  { eng: "ideal", kor: "이상적인이상" },
  { eng: "crop", kor: "농작물" },
  { eng: "ethnic", kor: "민족의" },
  { eng: "foretell", kor: "예언하다" },
  { eng: "wholesale", kor: "도매의, 대량의" },
  { eng: "debt", kor: "부채" },
  { eng: "representative", kor: "대표자" },
  { eng: "shift", kor: "바꾸다변화" },
  { eng: "strict", kor: "엄격한, 엄밀한" },
  { eng: "appliance", kor: "가전제품" },
  { eng: "furthermore", kor: "더욱이, 게다가" },
  { eng: "excess", kor: "초과, 과다" },
  { eng: "command", kor: "명령하다, 지휘하다명령, 지휘" },
  { eng: "ecosystem", kor: "생태계" },
  { eng: "fame", kor: "명성" },
  { eng: "oral", kor: "입의구술시험" },
  { eng: "drift", kor: "표류, 일반적인 경향떠돌다, 방황하다" },
  { eng: "outstanding", kor: "뛰어난, 눈에 띄는" },
  { eng: "mislead", kor: "잘못 판단하게 하다" },
  { eng: "dedicate", kor: "(시간, 노력을) 바치다" },
  { eng: "avoid", kor: "피하다, 방지하다" },
  { eng: "initial", kor: "초기의, 처음의 머리글자 (이니셜)" },
  { eng: "sink", kor: "가라앉다" },
  { eng: "beard", kor: "턱수염" },
  { eng: "haste", kor: "서두름" },
  { eng: "crush", kor: "으스러뜨리다, 빻다" },
  { eng: "confront", kor: "맞서다, 직면하다" },
  { eng: "destiny", kor: "운명" },
  { eng: "hardship", kor: "고난, 고통" },
  { eng: "escape", kor: "탈출하다, 벗어나다 탈출, 도피" },
  { eng: "valid", kor: "타당한, 유효한" },
  { eng: "entire", kor: "전체의, 완전한 전부, 전체" },
  { eng: "dispose", kor: "배치하다, 처리하다" },
  { eng: "optimal", kor: "최적의" },
  { eng: "hydrogen", kor: "수소" },
  { eng: "thread", kor: "실 실을 꿰다" },
  { eng: "dynasty", kor: "왕조" },
  { eng: "scatter", kor: "뿌리다, 흩어지다" },
  { eng: "gamble", kor: "돈을 걸다, 도박을 하다 도박" },
  { eng: "temper", kor: "성질, 기분" },
  { eng: "exist", kor: "존재하다, 살아가다" },
  { eng: "undoubtedly", kor: "의심할 여지없이, 확실히" },
  { eng: "raft", kor: "뗏목, 비닐보트" },
  { eng: "minimal", kor: "최소의, 아주 적은" },
  { eng: "soak", kor: "흠뻑 적시다" },
  { eng: "craft", kor: "공예, 기술 공들여 만들다" },
  { eng: "combat", kor: "전투 싸우다" },
  { eng: "cease", kor: "중단하다" },
  { eng: "ceiling", kor: "천장, 최고 한도" },
  { eng: "unify", kor: "통합하다, 통일하다" },
  { eng: "perspective", kor: "견해, 관점" },
  { eng: "doom", kor: "나쁜 운명 운명 짓다" },
  { eng: "bump", kor: "부딫치다" },
  { eng: "primary", kor: "주된, 초기의" },
  { eng: "genre", kor: "형식, 장르" },
  { eng: "erase", kor: "지우다" },
  { eng: "review", kor: "복습하다, 재검토하다 복습, 검토, 비평" },
  { eng: "vital", kor: "필수적인, 중요한, 생명 유지와 관련된" },
  { eng: "incident", kor: "사건, 일어난 일일어나기 쉬운" },
  { eng: "session", kor: "시간, 회의, 기간, 학기" },
  { eng: "obvious", kor: "분명한, 명백한" },
  { eng: "moderate", kor: "온건한, 적당한" },
  { eng: "budget", kor: "예산, 예산안" },
  { eng: "graze", kor: "풀을 뜯다, 방목하다" },
  { eng: "fragile", kor: "부서지기 쉬운" },
  { eng: "myth", kor: "신화, 사회적 통념" },
  { eng: "fur", kor: "부드러운 털, 모피" },
  { eng: "indifferent", kor: "무관심한" },
  { eng: "strain", kor: "긴장, 압박잡아당기다, 긴장시키다, 혹사하다" },
  { eng: "ingredient", kor: "재료, 성분" },
  { eng: "dismiss", kor: "묵살하다, 해고하다, 해산시키다" },
  { eng: "geometry", kor: "기하학" },
  { eng: "glacier", kor: "빙하" },
  { eng: "urge", kor: "촉구하다, 강요하다" },
  { eng: "celebrity", kor: "유명 인사, 명성" },
  { eng: "antique", kor: "고대의, 옛날의, 고풍의골동품" },
  { eng: "profit", kor: "이익, 이윤이익을 얻다" },
  { eng: "sphere", kor: "구, 구체" },
  { eng: "inherit", kor: "상속받다, 물려받다" },
  { eng: "disgrace", kor: "불명예, 수치" },
  { eng: "crawl", kor: "기어가다, 서행하다기어가기, 서행" },
  { eng: "scratch", kor: "긁다, 할퀴다긁힌 자국, 찰과상" },
  { eng: "diabetes", kor: "당뇨병" },
  { eng: "congestion", kor: "혼잡, 밀집" },
  { eng: "constitute", kor: "구성하다, 설립하다, 제정하다" },
  { eng: "flow", kor: "흐름흐르다" },
  { eng: "investigate", kor: "조사하다, 수사하다" },
  { eng: "barter", kor: "물물 교환, 교역품물물 교환하다" },
  { eng: "circular", kor: "원의, 순환의" },
  { eng: "chilly", kor: "쌀쌀한, 냉담한" },
  { eng: "ancestor", kor: "조상, 선조" },
  { eng: "fierce", kor: "사나운, 맹렬한" },
  { eng: "vague", kor: "희미한, 막연한, 모호한" },
  { eng: "rough", kor: "거친, 난폭한, 대강의" },
  { eng: "content", kor: "내용, 목차만족하는" },
  { eng: "obstacle", kor: "장애물, 방해가 되는 것" },
  { eng: "editorial", kor: "편집자의사설, 논설" },
  { eng: "abolish", kor: "폐지하다" },
  { eng: "assure", kor: "확실하게 하다, 보증하다" },
  { eng: "form", kor: "형태, 종류형성하다" },
  { eng: "gender", kor: "성, 성별" },
  { eng: "innovation", kor: "혁신" },
  { eng: "opponent", kor: "상대, 반대자반대하는" },
  { eng: "present", kor: "현재의현재, 선물제출하다 나타내다" },
  { eng: "fertile", kor: "비옥한, 기름진" },
  { eng: "emperor", kor: "황제" },
  { eng: "dwell", kor: "거주하다, 살다" },
  { eng: "chore", kor: "허드렛일, 집안일" },
  { eng: "rehearsal", kor: "리허설, 예행연습" },
  { eng: "fossil", kor: "화석" },
  { eng: "glitter", kor: "동사 반짝이다명사 반짝임" },
  { eng: "carve", kor: "새기다, 조각하다" },
  { eng: "decay", kor: "부패하다, 쇠퇴하다부패, 쇠퇴" },
  { eng: "protein", kor: "단백질" },
  { eng: "backward", kor: "뒤쪽으로 후방에 거꾸로" },
  { eng: "translate", kor: "번역하다, 옮기다" },
  { eng: "refresh", kor: "상쾌하게 하다, 새롭게 하다" },
  { eng: "tissue", kor: "(생물) 조직" },
  { eng: "lord", kor: "군주" },
  { eng: "substitute", kor: "대체하다대리자, 대체물" },
  { eng: "scan", kor: "정밀 검사하다, 유심히 쳐다보다" },
  { eng: "pottery", kor: "도자기, 도예" },
  { eng: "layer", kor: "층, 겹" },
  { eng: "property", kor: "재산, 소유물 , 부동산" },
  { eng: "justify", kor: "정당화하다" },
  { eng: "polish", kor: "닦다, 윤을 내다, (문장 등을)다듬다" },
  { eng: "flavor", kor: "맛동사 맛을 내다" },
  { eng: "imprint", kor: "찍다 감명시키다명사 찍은 자국, 인상" },
  { eng: "heritage", kor: "유산, 세습 재산" },
  { eng: "strive", kor: "노력하다, 애쓰다 , 투쟁하다" },
  { eng: "radiant", kor: "빛나는, 아주 밝은" },
  { eng: "exclaim", kor: "(감탄하며)외치다" },
  { eng: "asset", kor: "자산, 재산" },
  { eng: "portray", kor: "묘사하다, 설명하다, 초상을 그리다" },
  { eng: "administer", kor: "관리•운영하다, 집행하다, 주다" },
  { eng: "wage", kor: "급료" },
  { eng: "subscribe", kor: "정기 구독하다" },
  { eng: "architecture", kor: "건축학, 건축 양식" },
  { eng: "territory", kor: "영토, 영역" },
  { eng: "strategy", kor: "전략, 계획" },
  { eng: "hence", kor: "그러므로, 향후" },
  { eng: "panic", kor: "당황한 공황" },
  { eng: "wilderness", kor: "황무지" },
  { eng: "attract", kor: "끌다, 매혹하다" },
  { eng: "category", kor: "부류, 종류" },
  { eng: "murder", kor: "죽이다 살인" },
  { eng: "funeral", kor: "장례식 장례의" },
  { eng: "humiliation", kor: "창피 줌, 굴욕" },
  { eng: "ban", kor: "금지하다 금지" },
  { eng: "flush", kor: "물로 씻어내리다, (얼굴이) 붉어지다 물로 씻어냄, 홍조" },
  { eng: "omit", kor: "~을 생략하다" },
  { eng: "outcome", kor: "결과" },
  { eng: "despair", kor: "절망 절망하다" },
  { eng: "alert", kor: "조심하는 경고하다 경계" },
  { eng: "compact", kor: "아담한, 빽빽한 계약, 협정" },
  { eng: "likewise", kor: "마찬가지로" },
  { eng: "astonish", kor: "깜짝 놀라게 하다" },
  { eng: "optimistic", kor: "낙천적인" },
  { eng: "loyal", kor: "충성스러운" },
  { eng: "humid", kor: "습한" },
  { eng: "pretend", kor: "~인 척하다" },
  { eng: "graduate", kor: "졸업하다 졸업생" },
  { eng: "delicate", kor: "연약한, 섬세한, 미묘한" },
  { eng: "inflate", kor: "부풀리다, 과장하다, (가격을) 올리다" },
  { eng: "adequate", kor: "적절한" },
  { eng: "physician", kor: "의사" },
  { eng: "joint", kor: "관절 공동의" },
  { eng: "via", kor: "~을 경유해서, ~을 매개로 하여" },
  { eng: "passage", kor: "통로, (책의) 구절" },
  { eng: "prefer", kor: "~을 좋아하다" },
  { eng: "vessel", kor: "선박, 용기" },
  { eng: "restore", kor: "이전상태로 회복시키다" },
  { eng: "passive", kor: "소극적인,수동적인" },
  { eng: "experience", kor: "경험 경험하다" },
  { eng: "marble", kor: "대리석" },
  { eng: "classify", kor: "분류하다" },
  { eng: "fundamental", kor: "근본적인, 필수의" },
  { eng: "majesty", kor: "위엄, 장엄, 왕(M-)" },
  { eng: "intimate", kor: "친밀한, 친숙한" },
  { eng: "merit", kor: "장점, 가치" },
  { eng: "launch", kor: "시작하다, 출시하다 발사, 출시" },
  { eng: "conference", kor: "회의" },
  { eng: "reception", kor: "접수처, 환영연회" },
  { eng: "shrug", kor: "어깨를 으쓱하다 어깨를 으쓱하기" },
  { eng: "vicious", kor: "악랄한, 타락한" },
  { eng: "cherish", kor: "소중히 하다" },
  { eng: "accuse", kor: "고발하다, 비난하다" },
  { eng: "eternal", kor: "영원한" },
  { eng: "shrink", kor: "줄어들다, 피하다" },
  { eng: "colleague", kor: "동료" },
  { eng: "transmit", kor: "보내다, 전염시키다, 전도하다" },
  { eng: "copper", kor: "구리 구리의, 구릿빛의" },
  { eng: "orbit", kor: "궤도 궤도를 그리며 돌다" },
  { eng: "overwhelm", kor: "압도하다, 당황하게 하다" },
  { eng: "discard", kor: "폐기하다, 버리다, 처분하다" },
  { eng: "famine", kor: "기근, 굶주림, 기아" },
  { eng: "pill", kor: "알약" },
  { eng: "enhance", kor: "강화하다" },
  { eng: "immune", kor: "면역의, 면역성이 있는" },
  { eng: "superior", kor: "뛰어난, 눈에 띄는" },
  { eng: "string", kor: "끈 끈을 달다" },
  { eng: "cope", kor: "대처하다" },
  { eng: "raw", kor: "날것의, 가공하지 않은" },
  { eng: "apply", kor: "지원하다, 적용되다" },
  { eng: "cattle", kor: "소" },
  { eng: "loan", kor: "빌려주다 대여, 융자금" },
  { eng: "obedient", kor: "유순한, 순종하는" },
  { eng: "procedure", kor: "절차, 수술" },
  { eng: "bond", kor: "유대, 속박 유대를 맺다" },
  { eng: "angle", kor: "각도, 각 비스듬히 움직이다" },
  { eng: "subtle", kor: "미묘한, 교묘한, 예민한" },
  { eng: "depict", kor: "묘사하다, 그리다" },
  { eng: "radical", kor: "근본적인, 급진적인" },
  { eng: "therapy", kor: "치료법" },
  { eng: "caution", kor: "조심, 경고 경고하다" },
  { eng: "persist", kor: "고집하다, 지속하다" },
  { eng: "reverse", kor: "뒤집다, 후진하다 반대의 반대, 후진" },
  { eng: "support", kor: "떠받치, 지지 지지하다, 후원하다" },
  { eng: "mammal", kor: "포유동물" },
  { eng: "iceberg", kor: "빙산" },
  { eng: "monetary", kor: "화폐의" },
  { eng: "revise", kor: "개정하다, 수정하다" },
  { eng: "resent", kor: "분개하다, 화를 내다" },
  { eng: "superb", kor: "매우 뛰어난" },
  { eng: "abrupt", kor: "갑작스런, 퉁명스러운" },
  { eng: "diverse", kor: "다양한" },
  { eng: "internal", kor: "내부의, 체내의" },
  { eng: "gloom", kor: "우울, 어둠" },
  { eng: "refine", kor: "개선하다, 정제하다" },
  { eng: "dynamic", kor: "역동적인, 활발한" },
  { eng: "nerve", kor: "신경" },
  { eng: "prompt", kor: "신속한, 즉각적인 촉발하다, 자극하다" },
  { eng: "suspend", kor: "일시 중지하다, 보류하다, 정직(정학)시키다" },
  { eng: "control", kor: "통제하다, 지배하다 통제, 지배" },
  { eng: "distraction", kor: "집중을 방해하는 것" },
  { eng: "collapse", kor: "무너지다, (가격이) 폭락하다" },
  { eng: "monologue", kor: "독백" },
  { eng: "martial", kor: "군대의, 전쟁의" },
  { eng: "deliberate", kor: "고의의, 신중한" },
  { eng: "trigger", kor: "작동시키다, 촉발시키다 방아쇠, 계기" },
  { eng: "plot", kor: "줄거리, 음모 음모를 꾸미다" },
  { eng: "rod", kor: "막대, 낚싯대" },
  { eng: "Atlantic", kor: "대서양 대서양의" },
  { eng: "industry", kor: "산업" },
  { eng: "weird", kor: "이상한, 괴상한" },
  { eng: "suggest", kor: "제안하다, 암시하다" },
  { eng: "partial", kor: "부분적인, 편파적인" },
  { eng: "priceless", kor: "대단히 소중한" },
  { eng: "mutual", kor: "상호 간의, 공동의" },
  { eng: "fate", kor: "운명" },
  { eng: "booth", kor: "작은 공간" },
  { eng: "pursue", kor: "추구하다" },
  { eng: "prescribe", kor: "처방하다, 규정하다" },
  { eng: "erupt", kor: "(화산이) 폭발하다" },
  { eng: "insult", kor: "모욕하다 모욕, 모욕적인 말" },
  { eng: "gaze", kor: "응시하다 응시" },
  { eng: "supreme", kor: "최고 최고의" },
  { eng: "transaction", kor: "거래, 매매" },
  { eng: "sufficient", kor: "충분한" },
  { eng: "stable", kor: "안정된 마구간" },
  { eng: "sympathy", kor: "연민, 동의" },
  { eng: "by-product", kor: "부산물" },
  { eng: "edible", kor: "먹을 수 있는" },
  { eng: "federal", kor: "연방의, 연방 정부의" },
  { eng: "bud", kor: "싹, 봉오리, 친구" },
  { eng: "trivial", kor: "사소한" },
  { eng: "anxiety", kor: "걱정, 불안, 열망" },
  { eng: "tablet", kor: "알약" },
  { eng: "prepare", kor: "준비하다" },
  { eng: "trade", kor: "무역하다, 교환하다" },
  { eng: "liquid", kor: "액체 액체의, 유동적의" },
  { eng: "contend", kor: "싸우다, 주장하다" },
  { eng: "outlook", kor: "전망, 경치, 견해" },
  { eng: "roam", kor: "배회하다, 돌아다니다" },
  { eng: "decent", kor: "괜찮은, 예의 바른, 적절한" },
  { eng: "concern", kor: "걱정, 관심 걱정하다, 관심을 갖다" },
  { eng: "behalf", kor: "측, 편, 이익" },
  { eng: "suffer", kor: "고통 받다, 겪다" },
  { eng: "distortion", kor: "왜곡, 찌그러뜨림" },
  { eng: "infinite", kor: "무한한" },
  { eng: "anticipate", kor: "예상하다, 기대하다" },
  { eng: "symbolic", kor: "상징적인" },
  { eng: "municipal", kor: "지방 자치제의" },
  { eng: "phenomenon", kor: "현상" },
  { eng: "devote", kor: "(시간, 노력)쏟다" },
  { eng: "peasant", kor: "소작농" },
  { eng: "tenant", kor: "세입자" },
  { eng: "worthwhile", kor: "가치있는" },
  { eng: "pavement", kor: "포장도로" },
  { eng: "dioxide", kor: "(화학)이산화물" },
  { eng: "diminish", kor: "줄이다, 약화시키다" },
  { eng: "jealous", kor: "질투하는, 시기하는" },
  { eng: "limp", kor: "기운이 없는, 축 처진" },
  { eng: "exclude", kor: "제외하다, 차단하다" },
  { eng: "flexible", kor: "융통성 있는, 잘 구부러지는" },
  { eng: "nominate", kor: "지명하다" },
  { eng: "sacred", kor: "성스러운, 종교적인" },
  { eng: "context", kor: "맥락" },
  { eng: "complete", kor: "완벽한완료하다" },
  { eng: "race", kor: "경주, 인종경주하다" },
  { eng: "dominate", kor: "지배하다" },
  { eng: "vehicle", kor: "탈것" },
  { eng: "complain", kor: "불평하다" },
  { eng: "brochure", kor: "브로셔" },
  { eng: "force", kor: "힘강요하다" },
  { eng: "nest", kor: "둥지" },
  { eng: "gain", kor: "얻다" },
  { eng: "curriculum", kor: "교육 과정" },
  { eng: "sew", kor: "바느질하다" },
  { eng: "masculine", kor: "남자의" },
  { eng: "frown", kor: "눈살을 찌푸리다찡그린 얼굴" },
  { eng: "astound", kor: "놀라게 하다" },
  { eng: "dictator", kor: "독재자" },
  { eng: "assessment", kor: "평가" },
  { eng: "crucial", kor: "중대한, 결정적인" },
  { eng: "paralysis", kor: "마비" },
  { eng: "deck", kor: "(배의) 갑판" },
  { eng: "cheer", kor: "환호환호하다" },
  { eng: "miserable", kor: "비참한" },
  { eng: "tease", kor: "괴롭히다" },
  { eng: "aggressive", kor: "공격적인" },
  { eng: "cure", kor: "치료하다치료" },
  { eng: "attribute", kor: "~의 결과로 여기다속성" },
  { eng: "foster", kor: "육성하다" },
  { eng: "phychologist", kor: "심리학자" },
  { eng: "postpone", kor: "연기하다" },
  { eng: "rob", kor: "강탈하다, 훔치다" },
  { eng: "abuse", kor: "남용하다, 학대하다남용, 학대" },
  { eng: "unemployed", kor: "실업의" },
  { eng: "breakdown", kor: "고장, 쇠약" },
  { eng: "disguise", kor: "숨기다, 변장" },
  { eng: "blueprint", kor: "청사진" },
  { eng: "rear", kor: "뒤의뒤기르다" },
  { eng: "output", kor: "생산량" },
  { eng: "sermon", kor: "설교" },
  { eng: "sprout", kor: "싹이 트다. 싹" },
  { eng: "tin", kor: "주석, 양철" },
  { eng: "reform", kor: "개혁하다개혁," },
  { eng: "deal", kor: "다루다거래" },
  { eng: "recruit", kor: "모집하다신병" },
  { eng: "maintain", kor: "유지하다" },
  { eng: "workshop", kor: "작업장, 워크숍" },
  { eng: "patient", kor: "환자" },
  { eng: "convention", kor: "총회, 관습" },
  { eng: "devastate", kor: "황폐시키다" },
  { eng: "reap", kor: "수확하다" },
  { eng: "overlook", kor: "간과하다, 내려다보다" },
  { eng: "deliver", kor: "배달하다, (연설을)하다" },
  { eng: "reject", kor: "거부하다, 거절하다" },
  { eng: "nourish", kor: "영양분을 주다, 기르다" },
  { eng: "bay", kor: "만" },
  { eng: "stun", kor: "놀라게 하다" },
  { eng: "particular", kor: "특정한" },
  { eng: "bulletin", kor: "게시(물)" },
  { eng: "fluid", kor: "유동성의유동체" },
  { eng: "affair", kor: "일, 사건" },
  { eng: "dawn", kor: "새벽, 시작날이 새다" },
  { eng: "hostile", kor: "적대적인" },
  { eng: "characteristic", kor: "특징" },
  { eng: "respect", kor: "존경하다, (법 등을) 준수하다존경, 측면" },
  { eng: "await", kor: "기다리다" },
  { eng: "concrete", kor: "구체적인" },
  { eng: "lease", kor: "임대하다임대차 계약" },
  { eng: "racial", kor: "인종의" },
  { eng: "variable", kor: "변수. 변하기 쉬운, 변덕스러운" },
  { eng: "satisfy", kor: "만족시키다" },
  { eng: "rule", kor: "규칙, 지배지배하다" },
  { eng: "perseverance", kor: "인내심" },
  { eng: "fatal", kor: "치명적인" },
  { eng: "remove", kor: "제거하다, 치우다" },
  { eng: "invert", kor: "거꾸로 하다" },
  { eng: "tension", kor: "긴장" },
  { eng: "reign", kor: "통치, 지배" },
  { eng: "crack", kor: "금이 가다(갈라진 틈" },
  { eng: "startle", kor: "깜짝 놀라게 하다" },
  { eng: "discourage", kor: "낙담시키다, 말리다" },
  { eng: "compensate", kor: "보상하다" },
  { eng: "convert", kor: "전환시키다, 바꾸다" },
  { eng: "strike", kor: "치다" },
  { eng: "suppress", kor: "억압하다, 참다" },
  { eng: "core", kor: "핵심(의)" },
  { eng: "contribute", kor: "공헌하다" },
  { eng: "spear", kor: "창" },
  { eng: "renowned", kor: "명성 있는" },
  { eng: "era", kor: "시대" },
  { eng: "withdraw", kor: "인출하다" },
  { eng: "immigrate", kor: "이주하다" },
  { eng: "dignity", kor: "존엄" },
  { eng: "notify", kor: "통보하다, 알리다" },
  { eng: "animate", kor: "살아 있는" },
  { eng: "prevent", kor: "예방하다, 막다" },
  { eng: "bilingual", kor: "2개 국어의" },
  { eng: "mischief", kor: "장난, 해악" },
  { eng: "discriminate", kor: "차별하다, 구별하다" },
  { eng: "exemplify", kor: "예시하다" },
  { eng: "adhere", kor: "고수하다" },
  { eng: "judge", kor: "판단하다" },
  { eng: "peculiar", kor: "독특한" },
  { eng: "sake", kor: "위함, 목적" },
  { eng: "choke", kor: "질식시키다" },
  { eng: "folktale", kor: "민간 설화, 전설" },
  { eng: "simultaneously", kor: "동시에" },
  { eng: "range", kor: "범위" },
  { eng: "groom", kor: "신랑" },
  { eng: "supernatural", kor: "초자연적인" },
  { eng: "tender", kor: "부드러운" },
  { eng: "instinct", kor: "본능" },
  { eng: "gigantic", kor: "거대한" },
  { eng: "meditate", kor: "명상하다" },
  { eng: "mow", kor: "(풀을) 베다" },
  { eng: "evolve", kor: "진화하다, 발전하다" },
  { eng: "chase", kor: "추격하다, 쫓다" },
  { eng: "afflict", kor: "괴롭히다" },
  { eng: "literate", kor: "읽고 쓸 수 있는" },
  { eng: "coherent", kor: "통일성 있는, 조리 있는" },
  { eng: "intolerable", kor: "참을 수 없는" },
  { eng: "fountain", kor: "분수" },
  { eng: "bold", kor: "대담한, 선이 굵은" },
  { eng: "compliment", kor: "칭찬하다칭찬" },
  { eng: "summit", kor: "정상" },
  { eng: "troop", kor: "무리, 군대" },
  { eng: "alter", kor: "바꾸다, 변경하다" },
  { eng: "conceive", kor: "생각해 내다" },
  { eng: "durability", kor: "내구성" },
  { eng: "destroy", kor: "파괴하다" },
  { eng: "shallow", kor: "얕은, 피상적인" },
  { eng: "face", kor: "얼굴, 표면직면하다" },
  { eng: "promote", kor: "승진시키다" },
  { eng: "weep", kor: "울다" },
  { eng: "grasp", kor: "붙잡다" },
  { eng: "overall", kor: "전반적인, 전체의" },
  { eng: "superstition", kor: "미신" },
  { eng: "colony", kor: "식민지" },
  { eng: "absurd", kor: "불합리한, 우스꽝스러운" },
  { eng: "dormitory", kor: "기숙사" },
  { eng: "conduct", kor: "수행하다행위" },
  { eng: "prone", kor: "~하는 경향이 있는" },
  { eng: "conceal", kor: "숨기다" },
  { eng: "retreat", kor: "후퇴하다후퇴" },
  { eng: "compulsive", kor: "강제적인, 강박의" },
  { eng: "clinic", kor: "전문 병원, 개인 병원" },
  { eng: "banner", kor: "현수막" },
  { eng: "formulate", kor: "만들어내다, 공식화하다" },
  { eng: "vow", kor: "맹세(하다)" },
  { eng: "malnutrition", kor: "영양실조" },
  { eng: "relate", kor: "관련시키다" },
  { eng: "undergo", kor: "겪다" },
  { eng: "boast", kor: "자랑하다" },
  { eng: "neutral", kor: "중립의" },
  { eng: "stain", kor: "얼룩" },
  { eng: "incentive", kor: "장려책, 자극" },
  { eng: "float", kor: "뜨다, 떠다니다" },
  { eng: "tendency", kor: "경향" },
  { eng: "applause", kor: "박수갈채" },
  { eng: "wrestle", kor: "싸우다, 씨름하다" },
  { eng: "sensation", kor: "감각, 느낌" },
  { eng: "Confucian", kor: "공자의, 유교의" },
  { eng: "diameter", kor: "지름" },
  { eng: "ultrasound", kor: "초음파" },
  { eng: "propriety", kor: "적절성, 예의바름" },
  { eng: "anecdote", kor: "일화" },
  { eng: "shrub", kor: "관목" },
  { eng: "pledge", kor: "서약, 담보 서약하다" },
  { eng: "cost", kor: "가격, 비용 (가격, 비용이) 들다" },
  { eng: "geology", kor: "지질학" },
  { eng: "detect", kor: "찾아내다, 감지하다" },
  { eng: "temperate", kor: "절제하는, (기후가) 온화한" },
  { eng: "soar", kor: "급등하다, 날아오르다" },
  { eng: "mock", kor: "놀리다, 조롱하다 가짜의, 모조의" },
  { eng: "disclose", kor: "폭로하다, 드러내다" },
  { eng: "exhibit", kor: "전시하다 전시품" },
  { eng: "symptom", kor: "증상, 증후" },
  { eng: "manage", kor: "경영하다, 관리하다, 간신히 해내다" },
  { eng: "awkward", kor: "어색한, 서투른, 다루기 힘든" },
  { eng: "grind", kor: "갈다" },
  { eng: "expose", kor: "노출시키다, 폭로하다" },
  { eng: "closet", kor: "벽장" },
  { eng: "damp", kor: "축축한" },
  { eng: "script", kor: "대본" },
  { eng: "possibility", kor: "가능성, 기회" },
  { eng: "fad", kor: "(일시적인) 유행" },
  { eng: "sibling", kor: "형제, 자매" },
  { eng: "linger", kor: "남아 있다, 어슬렁거리다" },
  { eng: "flourish", kor: "번성하다, 건강하다" },
  { eng: "discharge", kor: "해고하다, 방출하다, 방면하다 해고, 방출, 면제" },
  { eng: "thorough", kor: "철저한" },
  { eng: "undertake", kor: "착수하다, 약속하다" },
  { eng: "cord", kor: "끈, 전기코드, (직물)코르덴 천 코르덴 천으로 만들어진" },
  { eng: "linguistic", kor: "언어의, 언어학의" },
  { eng: "remedy", kor: "치료" },
  { eng: "sole", kor: "유일한, 단독의" },
  { eng: "sophomore", kor: "(고교, 대학의) 2학년생" },
  { eng: "panel", kor: "판" },
  { eng: "suitor", kor: "소송인, 구혼자" },
  { eng: "pillar", kor: "기둥" },
  { eng: "explode", kor: "폭발하다" },
  { eng: "illusion", kor: "착각, 환각" },
  { eng: "draft", kor: "초고, 초안 초안을 그리다" },
  { eng: "crude", kor: "조잡한, 있는 그대로의" },
  { eng: "supplement", kor: "보완하다 보완, 보충" },
  { eng: "velocity", kor: "속도" },
  { eng: "tame", kor: "길들이다 길들여진" },
  { eng: "molecule", kor: "분자" },
  { eng: "reed", kor: "갈대 갈대의" },
  { eng: "dismay", kor: "실망 크게 실망시키다" },
  { eng: "diagnose", kor: "진단하다" },
  { eng: "versus", kor: "~와 대비하여" },
  { eng: "reservoir", kor: "저수지" },
  { eng: "conform", kor: "따르다, 순응하다" },
  { eng: "spacious", kor: "넓은, 훤히 트인" },
  { eng: "weave", kor: "(천을) 짜다 짜기" },
  { eng: "ceremony", kor: "의식, 식" },
  { eng: "motive", kor: "동기, 이유" },
  { eng: "prominent", kor: "두드러진" },
  { eng: "archaeology", kor: "고고학" },
  { eng: "rigid", kor: "엄격한, 굳은" },
  { eng: "inferior", kor: "열등한, 질 낮은" },
  { eng: "subtract", kor: "빼다" },
  { eng: "impulse", kor: "충동, 욕구, 추진력" },
  { eng: "utmost", kor: "최대한의  최대한도" },
  { eng: "proficient", kor: "숙달된" },
  { eng: "accumulate", kor: "모으다, 축적하다" },
  { eng: "navigate", kor: "길을 찾다, 항해하다" },
  { eng: "equity", kor: "자기자본, 공평" },
  { eng: "violate", kor: "위반하다, 침해하다" },
  { eng: "ambitious", kor: "야망을 가진" },
  { eng: "intact", kor: "온전한, 손상되지 않은" },
  { eng: "plea", kor: "애원, 탄원" },
  { eng: "attend", kor: "참석하다, 유의하다, 돌보다" },
  { eng: "trim", kor: "다듬다 잘 정돈된 정돈" },
  { eng: "embody", kor: "구체화하다, 포함하다" },
  { eng: "characteristic", kor: "특징, 특성 특유의" },
  { eng: "consist", kor: "~로 구성되다" },
  { eng: "boundary", kor: "경계, 한계" },
  { eng: "attack", kor: "공격하다 공격" },
  { eng: "confine", kor: "제한하다, 가두다" },
  { eng: "dispatch", kor: "급파, 발송 파견하다, 발송하다" },
  { eng: "regret", kor: "후회하다후회" },
  { eng: "coffin", kor: "관" },
  { eng: "divine", kor: "신성한" },
  { eng: "revenue", kor: "수익" },
  { eng: "corrupt", kor: "부패한, 타락한부패하다, 타락하다" },
  { eng: "probe", kor: "조사하다, 연구하다조사" },
  { eng: "factual", kor: "실제의" },
  { eng: "swamp", kor: "늪, 습지" },
  { eng: "expedition", kor: "탐험" },
  { eng: "abnormal", kor: "이상한, 비정상의" },
  { eng: "storage", kor: "저장소, 저장" },
  { eng: "revive", kor: "되살아나다" },
  { eng: "stool", kor: "(등받이 없는) 의자" },
  { eng: "hinder", kor: "방해하다" },
  { eng: "flattery", kor: "아첨" },
  { eng: "virtue", kor: "미덕" },
  { eng: "deadline", kor: "기한, 마감시간" },
  { eng: "equator", kor: "n.적도" },
  { eng: "cognitive", kor: "인식의" },
  { eng: "motion", kor: "운동, 동작동작을 해 보이다" },
  { eng: "humble", kor: "겸손한, 비천한" },
  { eng: "bounce", kor: "튀어 오르다, 깡충깡충 뛰다, (공이) 튀다" },
  { eng: "imprison", kor: "투옥하다" },
  { eng: "enlist", kor: "모집하다" },
  { eng: "hygiene", kor: "위생, 위생학" },
  { eng: "upcoming", kor: "다가오는" },
  { eng: "trace", kor: "자취, 흔적추적하다, 밝혀내다" },
  { eng: "pulse", kor: "맥박" },
  { eng: "controversy", kor: "논쟁, 언쟁, 논란" },
  { eng: "locate", kor: "(장소를) 찾아내다, -에 위치하다" },
  { eng: "patent", kor: "특허특허를 받은특허권을 얻다" },
  { eng: "lyric", kor: "n.가사" },
  { eng: "convenience", kor: "편의, 편리, 편의시설" },
  { eng: "rush", kor: "돌진하다, 급하게 가다돌진, 혼잡" },
  { eng: "carbon", kor: "탄소" },
  { eng: "contaminate", kor: "오염시키다, 더럽히다" },
  { eng: "external", kor: "외부의" },
  { eng: "herd", kor: "떼, 무리떼를 짓다" },
  { eng: "allocate", kor: "할당하다, 배분하다" },
  { eng: "gorgeous", kor: "아주 멋진, 화려한" },
  { eng: "confess", kor: "고백하다" },
  { eng: "subjective", kor: "주관적인" },
  { eng: "hell", kor: "지옥" },
  { eng: "acknowledge", kor: "인정하다" },
  { eng: "accord", kor: "일치하다, 조화하다일치, 합의" },
  { eng: "immense", kor: "엄청난" },
  { eng: "extract", kor: "추출하다, 추출물" },
  { eng: "sewage", kor: "하수, 오물" },
  { eng: "reconciliation", kor: "화해" },
  { eng: "amid", kor: "~의 한가운데" },
  { eng: "warrant", kor: "보증서, 영장, 정당한 이유" },
  { eng: "complement", kor: "보완하다" },
  { eng: "ceramic", kor: "도자기, 요업" },
  { eng: "license", kor: "면허, 인가면허를 주다, 허가하다" },
  { eng: "emerge", kor: "나타나다" },
  { eng: "halt", kor: "정지시키다정지, 멈춤" },
  { eng: "ivory", kor: "상아, 상아색" },
  { eng: "ponder", kor: "곰곰이 생각하다, 심사숙고하다" },
  { eng: "lottery", kor: "복권, 추첨" },
  { eng: "stroke", kor: "타격, 뇌졸증" },
  { eng: "burglar", kor: "강도" },
  { eng: "blame", kor: "비난하다, ~을 탓하다비난" },
  { eng: "transplant", kor: "이식하다" },
  { eng: "cluster", kor: "무리" },
  { eng: "borrow", kor: "빌리다" },
  { eng: "derive", kor: "끌어내다, ~에서 비롯되다" },
  { eng: "plague", kor: "전염병괴롭히다" },
  { eng: "certificate", kor: "증명서" },
  { eng: "deluxe", kor: "호화로운" },
  { eng: "convey", kor: "나르다,전달하다, (생각, 감정을) 전하다" },
  { eng: "depth", kor: "깊이" },
  { eng: "evaporate", kor: "증발하다" },
  { eng: "lame", kor: "절름발이의, 설득력이 없는" },
  { eng: "conduct", kor: "실시하다, 수행하다, 행동하다행위" },
  { eng: "sour", kor: "(맛이)신" },
  { eng: "repetitive", kor: "반복성의" },
  { eng: "oppress", kor: "n.억압하다" },
  { eng: "leftover", kor: "남은 음식, 잔재" },
  { eng: "embrace", kor: "포옹하다, 껴안다, 수용하다" },
  { eng: "blade", kor: "칼날" },
  { eng: "abundant", kor: "풍부한" },
  { eng: "duplicate", kor: "똑같은복사하다사본" },
  { eng: "remind", kor: "상기시키다, 생각나게 하다" },
  { eng: "altitude", kor: "고도" },
  { eng: "glimpse", kor: "흘끗 보다흘끗 봄" },
  { eng: "blend", kor: "섞다" },
  { eng: "swell", kor: "부풀다,팽창" },
  { eng: "grief", kor: "비탄, 큰 슬픔" },
  { eng: "beverage", kor: "음료수" },
  { eng: "warrior", kor: "전사, 용사" },
  { eng: "earn", kor: "(평판을) 얻다, 벌다" },
  { eng: "slice", kor: "(얇게 썬)조각얇게 썰다" },
  { eng: "exotic", kor: "이국적인" },
  { eng: "arrogant", kor: "거만한, 건방진" },
  { eng: "vanish", kor: "사라지다" },
  { eng: "rational", kor: "이성적인, 합리적인" },
  { eng: "predominant", kor: "우세한, 두드러진" },
  { eng: "cozy", kor: "안락한, 아늑한" },
  { eng: "broker", kor: "중개인, 브로커중개하다" },
  { eng: "auction", kor: "경매경매로 팔다" },
  { eng: "obsess", kor: "v.사로잡다, 강박 관념을 갖다" },
  { eng: "feed", kor: "~에 밥을 주다, ~에 먹이를 주다" },
  { eng: "outbreak", kor: "(전쟁, 사고등의) 발발" },
  { eng: "invent", kor: "발명하다" },
  { eng: "pioneer", kor: "개척자개척하다" },
  { eng: "assert", kor: "주장하다" },
  { eng: "undo", kor: "(잠긴 것을) 풀다, 원상태로 돌리다" },
  { eng: "bouquet", kor: "꽃다발" },
  { eng: "elaborate", kor: "정교한" },
  { eng: "toss", kor: "던지다던지기" },
  { eng: "retain", kor: "보유하다" },
  { eng: "radioactive", kor: "방사능의" },
  { eng: "buildup", kor: "축적" },
  { eng: "machinery", kor: "기계" },
  { eng: "passerby", kor: "통행인" },
  { eng: "auditorium", kor: "강당" },
  { eng: "lay", kor: "놓다, (알을) 낳다" },
  { eng: "neglect", kor: "무시하다소홀" },
  { eng: "feedback", kor: "피드백" },
  { eng: "promote", kor: "증진하다, 승진시키다" },
  { eng: "impair", kor: "손상시키다" },
  { eng: "metaphor", kor: "은유" },
  { eng: "dispense", kor: "분배하다, 나누어 주다" },
  { eng: "bruise", kor: "멍, 타박상" },
  { eng: "attorney", kor: "변호사, 대리인" },
  { eng: "framework", kor: "뼈대, 틀, 체제" },
  { eng: "heredity", kor: "n.유전" },
  { eng: "naive", kor: "순진한" },
  { eng: "shed", kor: "v.떨구다, 흘리다" },
  { eng: "metropolitan", kor: "대도시의" },
  { eng: "shield", kor: "방패보호하다" },
  { eng: "induce", kor: "유도하다, 설득하여 ~시키다" },
  { eng: "bazaar", kor: "시장, 바자" },
  { eng: "expel", kor: "추방하다" },
  { eng: "plow", kor: "쟁기갈다" },
  { eng: "prolong", kor: "연장하다" },
  { eng: "fluent", kor: "유창한" },
  { eng: "margin", kor: "가장자리" },
  { eng: "ecology", kor: "생태학, 생태" },
  { eng: "interior", kor: "내부내부의" },
  { eng: "ornament", kor: "장식장식하다" },
  { eng: "separate", kor: "분리하다" },
  { eng: "ripe", kor: "익은" },
  { eng: "vibrate", kor: "진동하다, 흔들다" },
  { eng: "urgent", kor: "긴급한" },
  { eng: "speculate", kor: "사색하다 ,투기하다" },
  { eng: "epidemic", kor: "전염병" },
  { eng: "precede", kor: "~에 앞서다" },
  { eng: "breathtaking", kor: "숨막히는" },
  { eng: "portfolio", kor: "포트폴리오" },
  { eng: "beware", kor: "주의하다" },
  { eng: "handcuff", kor: "수갑" },
  { eng: "overturn", kor: "전복시키다전복" },
  { eng: "pregnant", kor: "임신한" },
  { eng: "intelligence", kor: "지능" },
  { eng: "adapt", kor: "적응시키다" },
  { eng: "settle", kor: "정착하다" },
  { eng: "assassinate", kor: "암살하다" },
  { eng: "vapor", kor: "증기" },
  { eng: "tuition", kor: "수업료" },
  { eng: "literature", kor: "문학" },
  { eng: "loop", kor: "고리고리로 만들다" },
  { eng: "quote", kor: "인용하다인용구" },
  { eng: "inhale", kor: "들이쉬다, 흡입하다" },
  { eng: "prospect", kor: "전망, 가능성" },
  { eng: "anchor", kor: "닻,앵커" },
  { eng: "reference", kor: "참고, 언급" },
  { eng: "compound", kor: "혼합하다혼합물합성의" },
  { eng: "withstand", kor: "견디다, 버티다" },
  { eng: "implement", kor: "실행하다도구" },
  { eng: "anonymous", kor: "익명의" },
  { eng: "collide", kor: "충돌하다, 일치하지 않다" },
  { eng: "memorial", kor: "기념물" },
  { eng: "vacant", kor: "비어 있는, 빈자리의" },
  { eng: "technical", kor: "기술의" },
  { eng: "summon", kor: "소환하다" },
  { eng: "orchard", kor: "과수원" },
  { eng: "proportion", kor: "비율, 부분" },
  { eng: "antibiotic", kor: "항생 물질" },
  { eng: "overtake", kor: "따라잡다" },
  { eng: "resemble", kor: "~와 닮다" },
  { eng: "wander", kor: "(정처없이) 돌아다니다, 헤매다" },
  { eng: "compassion", kor: "동정" },
  { eng: "preoccupation", kor: "몰두, 집착" },
  { eng: "paste", kor: "풀로 붙이다풀" },
  { eng: "provoke", kor: "선동하다, 자극하다" },
  { eng: "wicked", kor: "사악한, 심술궂은" },
  { eng: "sprain", kor: "발목을 삐다" },
  { eng: "propaganda", kor: "선전" },
  { eng: "consistent", kor: "일관된" },
  { eng: "disrupt", kor: "붕과시키다" },
  { eng: "solitary", kor: "혼자의, 고립된" },
  { eng: "bury", kor: "(땅에)묻다" },
  { eng: "rust", kor: "녹녹이 슬다, 부식하다" },
  { eng: "discuss", kor: "토론하다" },
  { eng: "referee", kor: "심판" },
  { eng: "sector", kor: "분야, 지역" },
  { eng: "boost", kor: "밀어올리다상승" },
  { eng: "gymnastics", kor: "체조" },
  { eng: "gross", kor: "총합의총합" },
  { eng: "last", kor: "마지막, 지난" },
  { eng: "tariff", kor: "관세, 운임표" },
  { eng: "beloved", kor: "총애받는, 사랑하는" },
  { eng: "lyric", kor: "가사" },
  { eng: "yeast", kor: "이스트, 효모" },
  { eng: "skyscraper", kor: "고층건물" },
  { eng: "inquire", kor: "묻다" },
  { eng: "spade", kor: "삽, 스페이드" },
  { eng: "vacuum", kor: "진공, 공백" },
  { eng: "migrate", kor: "이주하다, 이동하다" },
  { eng: "spectacle", kor: "구경거리, 장관" },
  { eng: "surplus", kor: "여분, 나머지 나머지의" },
  { eng: "simulate", kor: "흉내내다, ~의 모의 실험을 하다" },
  { eng: "integration", kor: "통합" },
  { eng: "hypothesis", kor: "가설, 가정" },
  { eng: "affirm", kor: "단언하다" },
  { eng: "fortress", kor: "요새" },
  { eng: "reed", kor: "갈대" },
  { eng: "cue", kor: "신호, 단서 신호를 주다" },
  { eng: "mole", kor: "반점, 두더지" },
  { eng: "divide", kor: "나누다" },
  { eng: "inborn", kor: "타고난" },
  { eng: "overlap", kor: "겹치다, 중복되다" },
  { eng: "fatique", kor: "피곤" },
  { eng: "clone", kor: "복제, 복제품 복제하다" },
  { eng: "peel", kor: "껍질을 벗기다" },
  { eng: "ease", kor: "쉬움, 편안함 편하게 하다, 완화하다" },
  { eng: "overcome", kor: "극복하다" },
  { eng: "fund", kor: "자금" },
  { eng: "bias", kor: "편견, 선입견" },
  { eng: "vaccine", kor: "백신" },
  { eng: "tread", kor: "밟다 밟기" },
  { eng: "vomit", kor: "구토하다 구토" },
  { eng: "prophecy", kor: "예언" },
  { eng: "correspond", kor: "일치하다, 해당하다, 편지를 주고받다" },
  { eng: "cling", kor: "꼭 붙잡다, 달라붙다" },
  { eng: "mutation", kor: "돌연변이, 변형" },
  { eng: "obscure", kor: "모호한, 잘 알려지지 않은 모호하게 하다" },
  { eng: "tyrant", kor: "폭군" },
  { eng: "odd", kor: "이상한, 홀수의" },
  { eng: "intriguing", kor: "아주 흥미로운" },
  { eng: "restrain", kor: "억제하다, 제지하다" },
  { eng: "bundle", kor: "묶음" },
  { eng: "enclose", kor: "동봉하다, 둘러싸다" },
  { eng: "insert", kor: "삽입하다, 덧붙이다" },
  { eng: "keen", kor: "예민한, ~을열망하는" },
  { eng: "constrict", kor: "수축시키다" },
  { eng: "aid", kor: "도움, 지원" },
  { eng: "reputation", kor: "명성" },
  { eng: "measurement", kor: "측정" },
  { eng: "originate", kor: "유래하다" },
  { eng: "flour", kor: "밀가루" },
  { eng: "manipulate", kor: "조작하다, 잘 다루다" },
  { eng: "experiment", kor: "실험 실험하다" },
  { eng: "patriot", kor: "애국자" },
  { eng: "interchange", kor: "교환하다" },
  { eng: "intuitive", kor: "직감에 의한, 직관력 있는" },
  { eng: "garment", kor: "의류" },
  { eng: "spontaneous", kor: "자발적인, 즉흥적인" },
  { eng: "vertical", kor: "수직의, 세로의 수직선" },
  { eng: "testify", kor: "증언하다, 증명하다" },
  { eng: "mentor", kor: "조언자" },
  { eng: "vivid", kor: "생생한, 선명한" },
  { eng: "pasture", kor: "초원" },
  { eng: "crust", kor: "(빵, 파이의)껍질, 딱딱한 표면" },
  { eng: "comprehend", kor: "이해하다, 파악하다" },
  { eng: "plunge", kor: "뛰어들다, 급락하다" },
  { eng: "nasty", kor: "더러운, 비열한" },
  { eng: "appreciate", kor: "진가를 알아보다, 고맙게 여기다, 감상하다" },
  { eng: "emigrate", kor: "이민을 가다" },
  { eng: "deed", kor: "행동, 공적" },
  { eng: "skinny", kor: "깡마른, 옷이 몸에 딱 붙는" },
  { eng: "grill", kor: "그릴, 석쇠 그릴에 굽다" },
  { eng: "canal", kor: "운하, 수로" },
  { eng: "curse", kor: "저주" },
  { eng: "adverse", kor: "불리한, 반대의" },
  { eng: "censorship", kor: "검열관" },
  { eng: "forehead", kor: "이마" },
  { eng: "appetite", kor: "식욕, 욕망" },
  { eng: "flaw", kor: "결함, 결점" },
  { eng: "outgoing", kor: "외향적인, 사교적인" },
  { eng: "verbal", kor: "말의, 구두의" },
  { eng: "liberate", kor: "해방시키다" },
  { eng: "segregation", kor: "인종 차별, 차별정책, 분리" },
  { eng: "advance", kor: "전진하다, 진보하다발전, 전진, 진보" },
  { eng: "contemplate", kor: "~을 숙고하다, 심사숙고하다, 고려하다, 응시하다" },
  { eng: "underlying", kor: "기초를 이루는, 근본적인, 밑에 있는" },
  { eng: "academic", kor: "학문적인, 학구적인" },
  { eng: "stem", kor: "줄기생기다, 일어나다" },
  { eng: " irrigation", kor: "관개" },
  { eng: "consecutive", kor: "연이은, 연속적인" },
  { eng: "superficial", kor: "표면상의, 피상적인" },
  { eng: "refuge", kor: "피난처, 도피처, 보호구역" },
  { eng: "swear", kor: "맹세하다, 욕을 하다" },
  { eng: "allergy", kor: "알레르기" },
  { eng: "norm", kor: "표준, 규범" },
  { eng: "endeavor", kor: "노력하다, 시도하다노력, 시도" },
  { eng: "erect", kor: "똑바로 선세우다" },
  { eng: "feminine", kor: "여성의, 여성스러운" },
  { eng: "drowsy", kor: "졸리는" },
  { eng: "inspect", kor: "점검하다, 시찰하다" },
  { eng: "carriage", kor: "객차, 마차, 운반" },
  { eng: "primitive", kor: "원시의" },
  { eng: "compress", kor: "압축하다, 압박하다" },
  { eng: "govern", kor: "통치하다, 좌우하다" },
  { eng: "cemetery", kor: "공동묘지" },
  { eng: "shatter", kor: "산산이 부서지다" },
  { eng: "exaggerate", kor: "과장하다" },
  { eng: "random", kor: "무작위의" },
  { eng: "feast", kor: "잔치, 축제즐겁게 하다" },
  { eng: "commemorate", kor: "기념하다" },
  { eng: "steep", kor: "가파른, 비탈진몰두시키다, (액체에) 담그다" },
  { eng: "multitask", kor: "다중작업을 하다" },
  { eng: "toxic", kor: "유독한, 유독성의" },
  { eng: "stare", kor: "응시하다" },
  { eng: "chronic", kor: "만성적인" },
  { eng: "designate", kor: "지명하다, 지정하다" },
  { eng: "dramatic", kor: "극적인, 급격한, 감격적인" },
  { eng: "intense", kor: "강렬한, 극심한, 치열한" },
  { eng: "propaganda", kor: "선전 활동, 과장된 선전" },
  { eng: "numerous", kor: "다수의, 많은" },
  { eng: "shiver", kor: "몸을 떨다떨림" },
  { eng: "retarded", kor: "(정서•지능•학력) 발달이 뒤진" },
  { eng: "ongoing", kor: "진행 중인진행" },
  { eng: "mention", kor: "언급하다언급" },
  { eng: "executive", kor: "임원행정의, 관리의" },
  { eng: "chaos", kor: "혼돈, 혼란" },
  { eng: "microscope", kor: "현미경" },
  { eng: "belonging", kor: "소유물, 부속물" },
  { eng: "vulnerable", kor: "상처받기 쉬운, 취약한" },
  { eng: "implication", kor: "암시, 영향" },
  { eng: "appetite", kor: "식욕, 욕망" },
  { eng: "authentic", kor: "진정한, 진짜의" },
  { eng: "compel", kor: "강요하다, ~ 하게 만들다" },
  { eng: "transition", kor: "변화, 전환" },
  { eng: "index", kor: "(책 등의) 색인, 지표" },
  { eng: "incline", kor: "~쪽으로 기울다, 경사지다, 내키게 하다" },
  { eng: "attain", kor: "이루다, 달성하다" },
  { eng: "innate", kor: "타고난" },
  { eng: "ingenuity", kor: "기발한 재주, 독창성" },
  { eng: "record", kor: "기록, 증언기록하다, 녹음하다" },
  { eng: "bias", kor: "편견, 선입견" },
  { eng: "seize", kor: "붙잡다, 파악하다" },
  { eng: "screw", kor: "나사나사로 고정하다" },
  { eng: "savage", kor: "야만적인, 잔인한무참히 공격하다야만인" },
  { eng: "province", kor: "지역, 지방" },
  { eng: "coordinate", kor: "조직하다, 조정하다동등한" },
  { eng: "deficient", kor: "부족한, 불완전한" },
  { eng: "privilege", kor: "특권특권을 주다" },
  { eng: "preview", kor: "시사회, 시연, 미리보기" },
  { eng: "equivalent", kor: "동등한, ~에 상당하는동등한 것" },
  { eng: "loom", kor: "어렴풋이 나타나다 베틀" },
  { eng: "purple", kor: "자주색의" },
  { eng: "outlaw", kor: "범법자, 도망자금지하다, 법적으로 무효화하다" },
  { eng: "squeeze", kor: "(즙 등을) 짜내다" },
  { eng: "breakthrough", kor: "돌파구, 비약적 발전" },
  { eng: "consent", kor: "동의하다, 허락하다동의, 허락" },
  { eng: "orphan", kor: "고아" },
  { eng: "negotiate", kor: "협상하다" },
  { eng: "nuisance", kor: "골칫거리, 방해, 귀찮은 사람" },
  { eng: "recipe", kor: "요리법" },
  { eng: "deceive", kor: "속이다, 기만하다" },
  { eng: "sweep", kor: "쓸다, 휩쓸다" },
  { eng: "profile", kor: "옆모습, 윤곽, 인물 소개" },
  { eng: "enterprise", kor: "기업, 사업" },
  { eng: "successive", kor: "연속적인" },
  { eng: "paradox", kor: "역설, 모순되는 말" },
  { eng: "surpass", kor: "능가하다" },
  { eng: "correlation", kor: "상관 관계, 연관성" },
  { eng: "magnitude", kor: "중대성, 거대함" },
  { eng: "aesthetic", kor: "미의, 미학의" },
  { eng: "earnest", kor: "성실한, 진심어린" },
  { eng: "tremble", kor: "떨다, 흔들리다" },
  { eng: "slaughter", kor: "도살하다, 학살하다" },
  { eng: "surrender", kor: "항복하다, 양도하다항복, 양도" },
  { eng: "philosophy", kor: "철학, 인생관" },
  { eng: "deplete", kor: "고갈시키다" },
  { eng: "admire", kor: "존경하다" },
  { eng: "deform", kor: "불구로 만들다, <물리> 변형시키다" },
  { eng: "thrill", kor: "오싹하다 오싹함, 떨림" },
  { eng: "afford", kor: "~할 여유가 있다" },
  { eng: "blunt", kor: "무뚝뚝한, 직설적인" },
  { eng: "sprint", kor: "전력 질주하다" },
  { eng: "aid", kor: "도움, 지원" },
  { eng: "tense", kor: "긴장한(문법) 시제긴장시키다" },
  { eng: "amplify", kor: "증폭시키다, 확대하다" },
  { eng: "timber", kor: "목재" },
  { eng: "collaborate", kor: "협력하다" },
  { eng: "stance", kor: "태도, 자세" },
  { eng: "blow", kor: "(입으로) 불다, (바람이) 불다" },
  { eng: "ballot", kor: "투표투표하다" },
  { eng: "division", kor: "분할, 분열, 나눗셈" },
  { eng: "acquaintance", kor: "아는 사람" },
  { eng: "boil", kor: "끓다, 삶다" },
  { eng: "contradict", kor: "모순되다, 반박하다, 부정하다" },
  { eng: "burst", kor: "터지다, 갑자기 나타나다파열, 폭발" },
  { eng: "cast", kor: "던지다, 배역을 정하다, (빛을) 발하다출연자, 깁스" },
  { eng: "falsify", kor: "잘못을 입증하다" },
  { eng: "psychic", kor: "초자연적인, 마음의" },
  { eng: "paddle", kor: "노노를 저어 나아가다" },
  { eng: "steer", kor: "조종하다" },
  { eng: "affection", kor: "애착, 애정" },
  { eng: "bid", kor: "말하다" },
  { eng: "compost", kor: "퇴비, 두엄 퇴비를 만들다, 두엄을 끼얹다" },
  { eng: "temperament", kor: "기질" },
  { eng: "rent", kor: "임대료 임대하다" },
  { eng: "shred", kor: "조각조각으로 찢다" },
  { eng: "unpredictable", kor: "예측할 수 없는" },
  { eng: "tribute", kor: "경의의 표시" },
  { eng: "artery", kor: "동맥" },
  { eng: "inherent", kor: "내재하는" },
  { eng: "harass", kor: "희롱하다" },
  { eng: "narrative", kor: "서술의, 이야기로 이루어진 이야기" },
  { eng: "assemble", kor: "모으다, 조립하다" },
  { eng: "spike", kor: "못, 뾰족한것" },
  { eng: "sneak", kor: "몰래 들어가다" },
  { eng: "sophisticated", kor: "세련된, 정교한" },
  { eng: "handle", kor: "처리하다, 다루다" },
  { eng: "enlightenment", kor: "깨달음" },
  { eng: "cosmetic", kor: "화장품 허울뿐인, 표면적인" },
  { eng: "gracious", kor: "상냥한" },
  { eng: "aspire", kor: "열망하다" },
  { eng: "obstruct", kor: "방해하다, 가로막다" },
  { eng: "patrol", kor: "순찰, 순찰병" },
  { eng: "accelerate", kor: "가속하다, 촉진하다" },
  { eng: "heatstroke", kor: "일사병" },
  { eng: "oval", kor: "타원형의 타원형" },
  { eng: "veteran", kor: "베테랑, 참전용사" },
  { eng: "trail", kor: "흔적, 오솔길 끌다, 추적하다" },
  { eng: "vocation", kor: "천직, 직업" },
  { eng: "vegetarian", kor: "채식주의자" },
  { eng: "decode", kor: "해독하다" },
  { eng: "fellow", kor: "친구, 동료 동료의" },
  { eng: "mandate", kor: "권한, 명령 권한을 부여하다, 명령하다" },
  { eng: "perish", kor: "소멸하다, 죽다" },
  { eng: "inseparable", kor: "떼어낼 수 없는" },
  { eng: "domain", kor: "영역, 도메인" },
  { eng: "statesman", kor: "정치인" },
  { eng: "connotation", kor: "함축, 내포" },
  { eng: "stereotype", kor: "인습, 고정관념" },
  { eng: "hollow", kor: "속이 빈" },
  { eng: "structural", kor: "구조상의, 구조적인" },
  { eng: "mortgage", kor: "담보저당잡히다" },
  { eng: "inject", kor: "주사하다, 주입하다" },
  { eng: "crisis", kor: "위기" },
  { eng: "latter", kor: "나중의, 후자의(둘 중에서) 후자" },
  { eng: "illuminate", kor: "계몽하다" },
  { eng: "mimic", kor: "흉내내다" },
  { eng: "unearth", kor: "발굴하다" },
  { eng: "wail", kor: "울부짖다, 한탄하다" },
  { eng: "shudder", kor: "(공포, 추위로) 떨다떨림" },
  { eng: "stride", kor: "성큼성큼 걷다" },
  { eng: "applicant", kor: "지원자" },
  { eng: "disprove", kor: "반증하다" },
  { eng: "distrub", kor: "방해하다" },
  { eng: "hemisphere", kor: "(지구, 뇌의) 반구" },
  { eng: "recur", kor: "재발하다" },
  { eng: "elastic", kor: "탄력있는고무줄" },
  { eng: "counterpart", kor: "대응 하는 것" },
  { eng: "stubborn", kor: "완고한, 고집 센" },
  { eng: "suicide", kor: "자살" },
  { eng: "lure", kor: "유혹하다매력" },
  { eng: "underprivileged", kor: "혜택받지 못한" },
  { eng: "morale", kor: "사기, 의욕" },
  { eng: "examine", kor: "조사하다, 검사하다" },
  { eng: "compromise", kor: "타협하다타협" },
  { eng: "foremost", kor: "주요한" },
  { eng: "precaution", kor: "예방조치, 조심" },
  { eng: "torture", kor: "고문고문하다" },
  { eng: "entrust", kor: "위임하다" },
  { eng: "sway", kor: "흔들다, 동요시키다" },
  { eng: "religious", kor: "종교의, 신앙심이 깊은" },
  { eng: "obligation", kor: "의무, 책임" },
  { eng: "pest", kor: "해충, 유해동물" },
  { eng: "subdue", kor: "완화하다" },
  { eng: "incorporate", kor: "통합하다" },
  { eng: "regime", kor: "정권, 제도" },
  { eng: "terminate", kor: "끝내다" },
  { eng: "rebel", kor: "반역을 일으키다" },
  { eng: "meanwhile", kor: "한편" },
  { eng: "folklore", kor: "민속" },
  { eng: "vast", kor: "방대한" },
  { eng: "preliminary", kor: "예비의, 준비의예비 단계, 예선" },
  { eng: "theft", kor: "절도" },
  { eng: "painkiller", kor: "진통제" },
  { eng: "amend", kor: "수정하다" },
  { eng: "recess", kor: "휴식, 휴업" },
  { eng: "exploit", kor: "이용하다" },
  { eng: "autonomy", kor: "자율, 자치" },
  { eng: "outfit", kor: "복장과 장비" },
  { eng: "mourn", kor: "애도하다" },
  { eng: "evoke", kor: "이끌어내다" },
  { eng: "burden", kor: "부담~에게 부담을 지우다" },
  { eng: "latitude", kor: "위도" },
  { eng: "patch", kor: "조각, 작은 땅덧대다, 때우다" },
  { eng: "maternal", kor: "모성의" },
  { eng: "pharmacy", kor: "약국, 약학" },
  { eng: "marine", kor: "바다의, 해양의" },
  { eng: "prestigious", kor: "명성이 있는" },
  { eng: "friction", kor: "마찰, 충돌" },
  { eng: "defend", kor: "방어하다" },
  { eng: "fraud", kor: "사기, 사기꾼" },
  { eng: "easygoing", kor: "태평스러운" },
  { eng: "insomnia", kor: "불면증" },
  { eng: "intermediate", kor: "중급의, 중간의중급자" },
  { eng: "transport", kor: "수송하다수송" },
  { eng: "paradigm", kor: "패러다임, 사고체계" },
  { eng: "charge", kor: "요금, 책임(요금을) 청구하다" },
  { eng: "rapid", kor: "빠른" },
  { eng: "premature", kor: "조산한" },
  { eng: "pollute", kor: "오염시키다" },
  { eng: "altruism", kor: "이타주의" },
  { eng: "fiber", kor: "섬유질" },
  { eng: "irony", kor: "아이러니, 비꼼, 반어법" },
  { eng: "spectator", kor: "관중, 구경꾼" },
  { eng: "medieval", kor: "중세의" },
  { eng: "analogy", kor: "유사성" },
  { eng: "snatch", kor: "잡아채다" },
  { eng: "anthropology", kor: "인류학" },
  { eng: "outline", kor: "간략히 기술하다" },
  { eng: "slogan", kor: "슬로건, 선전 문구" },
  { eng: "composure", kor: "침착, 평정" },
  { eng: "incurable", kor: "불치의, 구제 불능의 불치 환자" },
  { eng: "parallel", kor: "평행의, 유사한 평행선 유사하다" },
  { eng: "indulge", kor: "탐닉하다.충족시키다" },
  { eng: "meadow", kor: "목초지, 초원" },
  { eng: "venture", kor: "모험하다 모험" },
  { eng: "deflect", kor: "빗나가다, 빗나가게 하다, 막다" },
  { eng: "adorable", kor: "귀여운, 사랑스러운" },
  { eng: "complacent", kor: "(스스로) 만족해하는, 현실에 안주하는" },
  { eng: "explicit", kor: "명백한, 분명한" },
  { eng: "sturdy", kor: "견고한, 튼튼한" },
  { eng: "primate", kor: "영장류" },
  { eng: "patron", kor: "후원자, 단골 손님" },
  { eng: "endure", kor: "참다, 인내하다, 견디다" },
  { eng: "manifest", kor: "명백하게 하다, 증명하다 명백한" },
  { eng: "imperial", kor: "제국의, 황제의" },
  { eng: "duration", kor: "지속, 지속 기간" },
  { eng: "populate", kor: "거주시키다" },
  { eng: "frugal", kor: "검소한, 절약하는" },
  { eng: "registration", kor: "기재, 등록" },
  { eng: "rejoice", kor: "크게 기뻐하다" },
  { eng: "comprise", kor: "포함하다, 구성하다" },
  { eng: "textile", kor: "직물의, 방직의 직물" },
  { eng: "lurk", kor: "숨다, 잠복하다" },
  { eng: "humanity", kor: "인류, 인간성, 인간애" },
  { eng: "approximate", kor: "(수량 등이) ~에 가까워지다 대략의" },
  { eng: "revenge", kor: "복수 복수하다" },
  { eng: "sarcastic", kor: "비꼬는, 풍자적인" },
  { eng: "terrain", kor: "지형, 지역, 분야, 범위" },
  { eng: "toll", kor: "사용세, 통행료, 종소리 요금으로 징수하다" },
  { eng: "warfare", kor: "전쟁, 전투, 교전 상태" },
  { eng: "mortal", kor: "죽을 운명의, 치명적인 인간" },
  { eng: "spouse", kor: "배우자" },
  { eng: "crispy", kor: "바삭바삭한, 부서지기 쉬운" },
  { eng: "statistical", kor: "통계적인, 통계상의" },
  { eng: "rubbish", kor: "쓰레기, 폐기물 혹평하다" },
  { eng: "stimulus", kor: "자극, 격려" },
  { eng: "clumsy", kor: "서투른, 어색한" },
  { eng: "subsequent", kor: "다음의, 그 이후의" },
  { eng: "relevant", kor: "관련된, 적절한" },
  { eng: "predator", kor: "포식자, 약탈자, 육식 동물" },
  { eng: "drain", kor: "물을 빼내다, 소모시키다 배수관" },
  { eng: "countless", kor: "셀 수 없는, 무수한" },
  { eng: "condense", kor: "농축하다, 요약하다" },
  { eng: "post", kor: "(벽 따위에) 붙이다, 우편" },
  { eng: "poise", kor: "균형을 잡다 균형, 평정" },
  { eng: "disciple", kor: "제자, 문하생" },
  { eng: "gust", kor: "돌풍, 질풍" },
  { eng: "collective", kor: "집합적인, 집단적인 집단" },
  { eng: "scope", kor: "(관찰, 활동의) 범위, 시야 조사하다" },
  { eng: "compatible", kor: "양립할 수 있는, 모순이 없는" },
  { eng: "border", kor: "경계, 가장자리, 국경 인접하다" },
  { eng: "frontier", kor: "국경 국경의, 최첨단의" },
  { eng: "withhold", kor: "억누르다, 억제하다, 보류하다" },
  { eng: "verdict", kor: "판결, 결정" },
  { eng: "stall", kor: "마구간, 우리 핑계를 대다" },
  { eng: "apparatus", kor: "장치, 기구, 조직" },
  { eng: "hail", kor: "우박, 싸락눈 우박이 내리다" },
  { eng: "outburst", kor: "폭발, 분출" },
  { eng: "vanity", kor: "허영심, 허무함" },
  { eng: "firsthand", kor: "직접의 직접, 바로" },
  { eng: "obesity", kor: "비만, 비대" },
  { eng: "dilemma", kor: "진퇴양난, 딜레마, 궁지" },
  { eng: "render", kor: "~이 되게 하다, 주다, 제공하다" },
  { eng: "indispensable", kor: "필수 불가결한 없어서는 안 될 것" },
  { eng: "outdated", kor: "구식의, 시대에 뒤진" },
  { eng: "bother", kor: "일부러~ 하다, 괴롭히다" },
  { eng: "counteract", kor: "(효력을) 중화시키다, 약화시키다" },
  { eng: "static", kor: "정적인, 고정된" },
  { eng: "sustain", kor: "유지하다, 지탱하다" },
  { eng: "posture", kor: "자세, 태도" },
  { eng: "discourse", kor: "담화, 강연" },
  { eng: "bribe", kor: "뇌물 뇌물을 주다" },
  { eng: "retention", kor: "보유, 기억력" },
  { eng: "valiant", kor: "용감한, 용맹스런" },
  { eng: "distress", kor: "고민, 고통 ~을 괴롭히다" },
  { eng: "nursery", kor: "육아실, 탁아소" },
  { eng: "juggle", kor: "잘 처리하다, 저글링하다" },
  { eng: "perspiration", kor: "땀, 노력" },
  { eng: "encircle", kor: "에워싸다, 둘러싸다" },
  { eng: "notion", kor: "개념, 의견" },
  { eng: "disgust", kor: "혐오감 역겹게 하다" },
  { eng: "fragment", kor: "일부분, 부서진 조각 산산이 부서지다" },
  { eng: "oversee", kor: "감독하다, 감시하다" },
  { eng: "creep", kor: "기다, (덩굴 등이) 얽히다 포복, 서행" },
  { eng: "clarify", kor: "명백히 하다" },
  { eng: "contagious", kor: "전염성의, 감염성의" },
  { eng: "deterioration", kor: "악화, (가치의) 하락, 저하" },
  { eng: "currency", kor: "통화, 통용" },
  { eng: "janitor", kor: "문지기, 관리인, (건물) 경비원" },
  { eng: "blush", kor: "얼굴을 붉히다, 부끄러워 하다" },
  { eng: "intervene", kor: "끼어들다, 개입하다, 방해하다" },
  { eng: "nomad", kor: "유목민, 방랑자" },
  { eng: "cuisine", kor: "요리, 요리법" },
  { eng: "dare", kor: "감히 ~하다" },
  { eng: "solvent", kor: "용해력이 있는, 지불 능력이 있는 용제, 용액" },
  { eng: "cultivate", kor: "경작하다, 양성하다, 계발하다" },
  { eng: "ascent", kor: "상승, 오름" },
  { eng: "advocate", kor: "옹호자, 지지자 지지하다" },
  { eng: "spur", kor: "자극, 고무 ~을 자극하다, (말에) 박차를 가하다" },
  { eng: "discern", kor: "식별하다, 분별하다, ~을 인식하다" },
  { eng: "scheme", kor: "계획, 체계 계획하다" },
  { eng: "weigh", kor: "무게를 달다" },
  { eng: "publicity", kor: "널리 알려짐, 명성, 광고, 선전" },
  { eng: "declare", kor: "선언하다, (세관에) 신고하다" },
  { eng: "brisk", kor: "활발한, 번창하는, 상쾌한" },
  { eng: "exile", kor: "망명, 망명자 망명시키다" },
  { eng: "whisper", kor: "속삭이다 속삭임" },
  { eng: "fling", kor: "내던지다, 돌진하다" },
  { eng: "deviation", kor: "변경, 일탈" },
  { eng: "dissolve", kor: "용해하다, 해산하다, 해소하다" },
  { eng: "constraint", kor: "강제, 압박, 제약" },
  { eng: "itch", kor: "가려움, 가렵다, (~하고 싶어) 못 견디다" },
  { eng: "unanimous", kor: "만장일치의, 합의의" },
  { eng: "delude", kor: "속이다, 착각하게 하다" },
  { eng: "dehydrate", kor: "탈수하다, 건조시키다" },
  { eng: "underneath", kor: "~의 아래에, 밑에" },
  { eng: "metabolism", kor: "물질대사, 신진대사" },
  { eng: "appoint", kor: "임명하다, (시간, 장소를) 정하다" },
  { eng: "pinch", kor: "꼬집다, 집다, 죄다" },
  { eng: "punctual", kor: "시간을 지키는" },
  { eng: "arbitrary", kor: "임의적인, 독단적인" },
  { eng: "catastrophe", kor: "대참사, 재앙" },
  { eng: "exert", kor: "(힘, 영향력을) 가하다, 발휘하다" },
  { eng: "aviate", kor: "조종하다, 비행하다" },
  { eng: "headquarters", kor: "본사, 본부" },
  { eng: "rectangular", kor: "직사각형의, 직각의" },
  { eng: "deledate", kor: "파견하다 사절, 대표" },
  { eng: "elect", kor: "선출하다" },
  { eng: "thorn", kor: "가시" },
  { eng: "empathize", kor: "공감하다" },
  { eng: "expertise", kor: "전문 지식" },
  { eng: "renovate", kor: "~을 새것으로 만들다, 수리하다" },
  { eng: "wrench", kor: "비틀다, 삐다  렌치, 쓰라림" },
  { eng: "interval", kor: "간격, 사이" },
  { eng: "degrade", kor: "저하시키다, 비하하다, 분해하다" },
  { eng: "report", kor: "보고서, 말대꾸 보고하다, 발표하다" },
  { eng: "asthma", kor: "천식" },
  { eng: "realm", kor: "영역, 왕국" },
  { eng: "segment", kor: "부분, 조각" },
  { eng: "coexist", kor: "공존하다" },
  { eng: "hospitality", kor: "환대, 후한 대접" },
  { eng: "estate", kor: "재산, 토지" },
  { eng: "displace", kor: "옮겨 놓다, 대체하다" },
  { eng: "cripple", kor: "불구자, 지체 부자유자 ~을 불구로 만들다, 손상시키다" },
  { eng: "drawback", kor: "문제점, 결점, 장애" },
  { eng: "tactics", kor: "방안, 전술" },
  { eng: "dread", kor: "두려워하다, 무서워하다 두려움, 공포" },
  { eng: "dispute", kor: "논쟁하다, 토의하다 논쟁, 분쟁" },
  { eng: "console", kor: "위로하다" },
  { eng: "stack", kor: "더미, 산더미 쌓아 올리다" },
  { eng: "cynical", kor: "냉소적인, 비관적인" },
  { eng: "reprove", kor: "꾸짖다, 책망하다" },
  { eng: "verify", kor: "입증하다" },
  { eng: "engross", kor: "열중하게 하다" },
  { eng: "bulk", kor: "크기, 부피, 대부분 부피가 커지다, 덩어리가 되다" },
  { eng: "despise", kor: "경멸하다" },
  { eng: "manuscript", kor: "원고, 필사본" },
  { eng: "flee", kor: "달아나다" },
  { eng: "prehistoric", kor: "선사시대의" },
  { eng: "barrel", kor: "통, 배럴" },
  { eng: "predecessor", kor: "이전 형태, 전임자" },
  { eng: "alienate", kor: "소외시키다, 멀리하다" },
  { eng: "preclaim", kor: "선언하다, 선포하다" },
  { eng: "subordinate", kor: "하위의, 부차적인하급자하위에 두다" },
  { eng: "furnish", kor: "(가구를) 비치하다, 제공하다, 갖추다" },
  { eng: "fume", kor: "씩씩대다, 연기를 내뿜다연기" },
  { eng: "staple", kor: "주된, 주요한주성분" },
  { eng: "dimension", kor: "크기, 측면, 치수, 차원" },
  { eng: "dispersal", kor: "분산, 확산" },
  { eng: "eloquent", kor: "웅변의, 달변의, 연설을 잘 하는, 표현이 풍부한" },
  { eng: "innermost", kor: "가장 깊숙한가장 깊은 부분" },
  { eng: "hazardous", kor: "위험한, 해로운" },
  { eng: "skull", kor: "두개골" },
  { eng: "detergent", kor: "세제" },
  { eng: "brutal", kor: "야만적인, 잔혹한" },
  { eng: "rash", kor: "반점, 발진경솔한" },
  { eng: "bypass", kor: "우회로우회하다" },
  { eng: "accommodate", kor: "수용하다, 적응하다" },
  { eng: "tact", kor: "재치, 기지" },
  { eng: "monotonous", kor: "단조로운, 지루한" },
  { eng: "perpetual", kor: "영원한, 끊임없는" },
  { eng: "eligible", kor: "~을 할 수 있는, 유능한, 자격의, 자격이 있는" },
  { eng: "legacy", kor: "유물, 유산" },
  { eng: "melancholy", kor: "우울한우울함" },
  { eng: "simplicity", kor: "단순함, 간단" },
  { eng: "hierarchy", kor: "계층, 계급, 지배층, 체계" },
  { eng: "reside", kor: "거주하다" },
  { eng: "enact", kor: "제정하다, 상영하다" },
  { eng: "burnout", kor: "극도의 피로, 쇠진" },
  { eng: "legitimate", kor: "타당한, 합법적인, 정당한" },
  { eng: "shuffle", kor: "발을 끌며 걷다, 뒤섞다" },
  { eng: "summarize", kor: "요약하다" },
  { eng: "eject", kor: "쫓아내다, 튀어나오게 하다" },
  { eng: "intersection", kor: "교차로, 교차함" },
  { eng: "quest", kor: "탐색, 탐구, 추구, 찾음" },
  { eng: "linear", kor: "직선의, 길이의" },
  { eng: "landslide", kor: "산사태, (선거에서) 압도적 승리" },
  { eng: "plausible", kor: "그럴듯한, 이치에 맞는" },
  { eng: "endow", kor: "기부하다, ~에게 부여하다" },
  { eng: "extrinsic", kor: "외적인, 외부의" },
  { eng: "merge", kor: "합병하다, 차차 변하다" },
  { eng: "frantic", kor: "광란의, 미친" },
  { eng: "moan", kor: "신음, 투덜거림 신음하다, 불평하다" },
  { eng: "merchandise", kor: "(집학적) 상품 거래하다" },
  { eng: "respectively", kor: "각각, 저마다" },
  { eng: "yearn", kor: "그리워하다, 열망하다" },
  { eng: "conviction", kor: "확신, 유죄 판결" },
  { eng: "stout", kor: "뚱뚱한, (옷 등이) 튼튼한" },
  { eng: "reckon", kor: "세다, 계산하다, 생각하다" },
  { eng: "enchant", kor: "매혹하다, ~에게 마법을 걸다" },
  { eng: "entail", kor: "수반하다, 의미하다, 필요로 하다" },
  { eng: "demolish", kor: "파괴하다, 폐지하다" },
  { eng: "degenerate", kor: "퇴보하다, 타락하다" },
  { eng: "sentiment", kor: "감상, 정서" },
  { eng: "offspring", kor: "자식, 새끼, 성과" },
  { eng: "detest", kor: "혐오하다, 미워하다" },
  { eng: "tackle", kor: "(일, 문제를) 다루다, 처리하다 도구, (축구의) 태클" },
  { eng: "defy", kor: "물리치다, (공공연히) 무시하다, 반항하다" },
  { eng: "inference", kor: "추론" },
  { eng: "refraction", kor: "(빛, 소리 따위의) 굴절" },
  { eng: "dusk", kor: "땅거미, 어스름" },
  { eng: "detach", kor: "떼어내다, 분리하다" },
  { eng: "antagonist", kor: "적대자, 라이벌" },
  { eng: "thrust", kor: "밀다, 밀치다, 찌르다" },
  { eng: "creed", kor: "신념, (종교의) 교의" },
  { eng: "equate", kor: "동일시하다, 일치하다" },
  { eng: "misplace", kor: "잘못두다" },
  { eng: "auditory", kor: "귀의, 청각의, 음향의" },
  { eng: "missionary", kor: "선교사" },
  { eng: "cosmopolitan", kor: "세계적인, 세계주의의 세계인, 국제인" },
  { eng: "secondhand", kor: "중고의, 간접적인" },
  { eng: "multiple", kor: "복합적인, 다수의, 다양한 (수학) 배수" },
  { eng: "embed", kor: "깊숙이 박다, 깊이 간직하다, 내재하다" },
  { eng: "propel", kor: "나아가게 하다, 추진하다" },
  { eng: "reptile", kor: "파충류" },
  { eng: "erosion", kor: "부식, 침식" },
  { eng: "feat", kor: "위업, 공적, 솜씨" },
  { eng: "utensil", kor: "가정용품, 기구, 도구" },
  { eng: "penetrate", kor: "관통하다, 꿰뚫다, 침투하다" },
  { eng: "intrude", kor: "침범하다, 방해하다" },
  { eng: "notable", kor: "주목할 만한, 유명한" },
  { eng: "grumble", kor: "불평하다, 투덜거리다 불평" },
  { eng: "landfill", kor: "쓰레기 매립지" },
  { eng: "scrutiny", kor: "(정밀) 조사, 철저한 검토" },
  { eng: "reckless", kor: "무모한, 부주의한, 신중하지 못한" },
  { eng: "synthetic", kor: "합성의, 종합적인" },
  { eng: "productive", kor: "생산하는, 생산적인" },
  { eng: "outset", kor: "착수, 발단, 시작, 처음" },
  { eng: "peril", kor: "위험" },
  { eng: "pitfall", kor: "위험, 함정" },
  { eng: "kidnap", kor: "납치하다 유괴" },
  { eng: "liable", kor: "책임이 있는, ~하기 쉬운" },
  { eng: "insane", kor: "정신 이상의, 미친, 비상식적인" },
  { eng: "rage", kor: "격노 격노하다" },
  { eng: "radius", kor: "반지름" },
  { eng: "hybrid", kor: "잡종, 혼합물" },
  { eng: "uncover", kor: "폭로하다, 덮개를 벗기다" },
  { eng: "limb", kor: "사지, 팔다리, 나뭇가지" },
  { eng: "setback", kor: "좌절, 차질, 방해, 실패" },
  { eng: "prudent", kor: "신중한" },
  { eng: "solidify", kor: "굳어지다, 굳히다, 확고히 하다" },
  { eng: "grudge", kor: "원한, 유감" },
  { eng: "lessen", kor: "줄이다" },
  { eng: "tangle", kor: "얽히게 하다, 혼란시키다" },
  { eng: "subsidy", kor: "보조금, 장려금" },
  { eng: "ambiguous", kor: "애매모호한, 불명확한" },
  { eng: "enthusiasm", kor: "열광, 열정, 열광하는 대상" },
  { eng: "bankruptcy", kor: "파산" },
  { eng: "pollination", kor: "수분" },
  { eng: "prosper", kor: "번영하다, 번창하다" },
  { eng: "phase", kor: "단계" },
  { eng: "veterinarian", kor: "수의사" },
  { eng: "counterattack", kor: "반격, 연습 반격하다, 역습하다" },
  { eng: "cumulative", kor: "누적되는" },
  { eng: "infrastructure", kor: "(사회) 기반 시설, 하부 조직" },
  { eng: "wound", kor: "상처를 입히다, 부상하게 하다 부상, 상처" },
  { eng: "discrete", kor: "별개의" },
  { eng: "fluctuation", kor: "변동, 동요" },
];